# Generated by Django 5.2.17 on 2026-10-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarshPlusItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="شناسه نزد فرش پلاس"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        blank=True,
                        help_text="خالی = طبق تنظیم ارسال خودکار",
                        null=True,
                        verbose_name="ارسال",
                    ),
                ),
                (
                    "in_feed",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="نمایش در فید"
                    ),
                ),
                (
                    "post_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="شناسهٔ پست"
                    ),
                ),
                (
                    "post_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="آدرس پست"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, verbose_name="وضعیت"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین ارسال"
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=500, verbose_name="خطا"),
                ),
                ("images_hash", models.CharField(blank=True, max_length=64)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "queued",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="در صف"
                    ),
                ),
                ("mode", models.CharField(default="auto", max_length=10)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_try_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farshplus",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول در فرش پلاس",
                "verbose_name_plural": "محصولات در فرش پلاس",
            },
        ),
        migrations.CreateModel(
            name="FarshPlusSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="اتصال فعال باشد"),
                ),
                (
                    "url",
                    models.URLField(
                        default="https://farshplus.com", verbose_name="آدرس فرش پلاس"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="کلید API"
                    ),
                ),
                (
                    "auto_sync",
                    models.BooleanField(
                        default=True, verbose_name="ارسال خودکار محصولات تازه و تغییرات"
                    ),
                ),
                (
                    "default_in_feed",
                    models.BooleanField(
                        default=True,
                        help_text="ارسال گروهی همیشه بی\u200cصدا و بدون نمایش در فید است",
                        verbose_name="نمایش در فید (برای ارسال\u200cهای تکی)",
                    ),
                ),
                (
                    "hashtags",
                    models.BooleanField(
                        default=True,
                        verbose_name="دسته\u200cها و برچسب\u200cها به\u200cعنوان هشتگ",
                    ),
                ),
                (
                    "hide_out_of_stock",
                    models.BooleanField(
                        default=True, verbose_name="محصول ناموجود در فرش پلاس پنهان شود"
                    ),
                ),
                (
                    "max_images",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="حداکثر تصویر هر محصول"
                    ),
                ),
                (
                    "rate_limited_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="توقف تا"),
                ),
                ("connection", models.JSONField(blank=True, default=dict)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                ("last_refresh_at", models.DateTimeField(blank=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="خالی = همهٔ دسته\u200cها",
                        to="catalog.category",
                        verbose_name="فقط این دسته\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات فرش پلاس",
                "verbose_name_plural": "تنظیمات فرش پلاس",
            },
        ),
    ]
