# Generated by Django 5.2.17 on 2026-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farshplus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farshplusitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PUBLISHED", "منتشر شده"),
                    ("PROCESSING", "در حال پردازش"),
                    ("PENDING_REVIEW", "در انتظار بررسی"),
                    ("HIDDEN", "پنهان (ناموجود)"),
                    ("ARCHIVED", "بایگانی"),
                    ("REMOVED", "حذف شده"),
                    ("QUEUED", "در صف ارسال"),
                    ("ERROR", "خطا"),
                    ("", "ارسال نشده"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="وضعیت",
            ),
        ),
    ]
