# Generated by Django 5.2.17 on 2026-10-08 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0010_fill_search"),
        ("shop", "0008_offer_no_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="همکاری در فروش فعال است"
                    ),
                ),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False,
                        help_text="خاموش: هر ثبت\u200cنام باید در پنل تأیید شود (پیشنهادی).",
                        verbose_name="تأیید خودکار بازاریاب\u200cهای تازه",
                    ),
                ),
                (
                    "attribution_days",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="خرید مشتری تا این تعداد روز بعد از آخرین ورود با پیوند بازاریاب، به نام او ثبت می\u200cشود.",
                        verbose_name="ماندگاری پیوند (روز)",
                    ),
                ),
                (
                    "tier_period",
                    models.CharField(
                        choices=[
                            ("month", "فروش همان ماه (هر ماه شمسی از صفر)"),
                            ("all", "کل فروش از ابتدای همکاری"),
                        ],
                        default="month",
                        max_length=10,
                        verbose_name="پله بر اساس",
                    ),
                ),
                (
                    "tier_mode",
                    models.CharField(
                        choices=[
                            (
                                "whole",
                                "کل فروش دوره با درصد پله\u200cای که به آن رسیده",
                            ),
                            ("bracket", "پلکانی (هر بخش از فروش با درصد پلهٔ خودش)"),
                        ],
                        default="whole",
                        help_text="مثال با پلهٔ ۱٫۵٪ تا ۱۵۰ میلیون و ۲٪ بالاتر، برای ۲۰۰ میلیون فروش: روش اول ۲٪ × ۲۰۰ = ۴ میلیون؛ روش پلکانی ۱٫۵٪ × ۱۵۰ + ۲٪ × ۵۰ = ۳٫۲۵ میلیون.",
                        max_length=10,
                        verbose_name="روش محاسبهٔ پله",
                    ),
                ),
                (
                    "new_customers_only",
                    models.BooleanField(
                        default=False,
                        help_text="روشن: برای مشتری\u200cای که قبلاً از ایران کارپت خرید کرده پورسانت ثبت نمی\u200cشود.",
                        verbose_name="فقط مشتری تازه",
                    ),
                ),
                (
                    "min_payout",
                    models.PositiveBigIntegerField(
                        default=1000000, verbose_name="حداقل مبلغ تسویه (تومان)"
                    ),
                ),
                (
                    "coupon_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="برای اینستاگرام و جاهایی که پیوند کلیک\u200cخور نیست: مشتری کد را در سبد خرید می\u200cزند، تخفیف می\u200cگیرد و خرید به نام بازاریاب ثبت می\u200cشود.",
                        verbose_name="کد تخفیف اختصاصی برای هر بازاریاب",
                    ),
                ),
                (
                    "coupon_percent",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="درصد تخفیف کد بازاریاب"
                    ),
                ),
                (
                    "coupon_max",
                    models.PositiveBigIntegerField(
                        default=2000000,
                        help_text="۰ یعنی بی\u200cسقف",
                        verbose_name="سقف تخفیف کد بازاریاب (تومان)",
                    ),
                ),
                (
                    "short_domain",
                    models.CharField(
                        default="crpt.it",
                        help_text="باید رکورد DNS آن به سرور اشاره کند. خالی: پیوندها با دامنهٔ خود سایت ساخته می\u200cشوند.",
                        max_length=60,
                        verbose_name="دامنهٔ پیوند کوتاه",
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        default="- پورسانت فقط برای سفارش\u200cهایی است که پرداخت و تحویل شده\u200cاند؛ سفارش لغو یا مرجوع\u200cشده پورسانت ندارد.\n- مشتری از اولین ورود با پیوند شما تا {روز} روز به نام شما ثبت می\u200cشود؛ اگر با پیوند همکار دیگری بیاید، آخرین پیوند حساب است.\n- خرید خودتان (با حساب یا شمارهٔ خودتان) پورسانت ندارد.\n- تبلیغ با نام «ایران کارپت» در گوگل ادز، ساختن صفحه یا حساب با نام و نشان ایران کارپت، و پیامک یا ایمیل انبوه ناخواسته ممنوع است.\n- قیمت، تخفیف یا شرایطی جز آنچه در سایت آمده به مشتری وعده ندهید.\n- تسویه پس از رسیدن مانده به حداقل مبلغ تسویه، به شماره شبای ثبت\u200cشده به نام خودتان انجام می\u200cشود.",
                        help_text="هر خط یک بند. {روز} = ماندگاری پیوند",
                        verbose_name="قوانین همکاری",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات همکاری در فروش",
                "verbose_name_plural": "تنظیمات همکاری در فروش",
            },
        ),
        migrations.CreateModel(
            name="CommissionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_sales",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="پله از این مبلغ شروع می\u200cشود و تا شروع پلهٔ بعدی ادامه دارد. پلهٔ اول را ۰ بگذارید.",
                        unique=True,
                        verbose_name="از فروش (تومان)",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="درصد پورسانت"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="اختیاری؛ مثل «برنزی»، «نقره\u200cای»",
                        max_length=40,
                        verbose_name="نام پله",
                    ),
                ),
            ],
            options={
                "verbose_name": "پلهٔ پورسانت",
                "verbose_name_plural": "پله\u200cهای پورسانت",
                "ordering": ["min_sales"],
            },
        ),
        migrations.CreateModel(
            name="Affiliate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="حروف کوچک انگلیسی، عدد و _ (۳ تا ۲۰ حرف)؛ در پیوند کوتاه می\u200cآید: crpt.it/کد",
                        max_length=20,
                        unique=True,
                        verbose_name="کد پیوند",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تأیید"),
                            ("active", "فعال"),
                            ("rejected", "رد شده"),
                            ("blocked", "متوقف"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="شهر"),
                ),
                (
                    "channels",
                    models.TextField(
                        blank=True,
                        help_text="صفحهٔ اینستاگرام، کانال، فروشگاه، دکوراسیون داخلی…",
                        verbose_name="کجا معرفی می\u200cکند",
                    ),
                ),
                (
                    "sheba",
                    models.CharField(
                        blank=True,
                        help_text="IR و ۲۴ رقم",
                        max_length=26,
                        verbose_name="شماره شبا",
                    ),
                ),
                (
                    "account_holder",
                    models.CharField(blank=True, max_length=120, verbose_name="به نام"),
                ),
                (
                    "custom_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اگر پر باشد، به\u200cجای پله\u200cها همین درصد برای همهٔ فروش\u200cهای این همکار حساب می\u200cشود.",
                        max_digits=5,
                        null=True,
                        verbose_name="درصد اختصاصی",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ ثبت\u200cنام",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliates",
                        to="shop.coupon",
                        verbose_name="کد تخفیف اختصاصی",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "همکار فروش",
                "verbose_name_plural": "همکاران فروش",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=300)),
                ("visitor", models.CharField(db_index=True, max_length=16)),
                ("referer", models.CharField(blank=True, max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="affiliate.affiliate",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "ورود با پیوند",
                "verbose_name_plural": "ورودها با پیوند",
            },
        ),
        migrations.CreateModel(
            name="CustomerRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="affiliate.affiliate",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_ref",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="کد پیگیری واریز"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="توضیح"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ واریز"
                    ),
                ),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="affiliate.affiliate",
                        verbose_name="همکار",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسویه",
                "verbose_name_plural": "تسویه\u200cها",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("link", "پیوند"),
                            ("coupon", "کد تخفیف همکار"),
                            ("account", "پیوند (حساب مشتری)"),
                            ("manual", "دستی"),
                        ],
                        default="link",
                        max_length=10,
                        verbose_name="از راه",
                    ),
                ),
                (
                    "base",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مبلغ فروش (تومان)"
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="درصد"
                    ),
                ),
                (
                    "amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="پورسانت (تومان)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "منتظر پرداخت مشتری"),
                            ("pending", "پرداخت شد؛ منتظر تحویل"),
                            ("approved", "قابل تسویه"),
                            ("paid", "تسویه شد"),
                            ("cancelled", "لغو شد"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "period",
                    models.CharField(db_index=True, max_length=7, verbose_name="دوره"),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="روشن: پورسانت دیگر خودکار حساب نمی\u200cشود.",
                        verbose_name="مبلغ دستی",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="affiliate.affiliate",
                        verbose_name="همکار",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission",
                        to="shop.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="affiliate.payout",
                        verbose_name="تسویه",
                    ),
                ),
            ],
            options={
                "verbose_name": "پورسانت",
                "verbose_name_plural": "پورسانت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=400)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="affiliate.affiliate",
                    ),
                ),
            ],
            options={
                "unique_together": {("affiliate", "path")},
            },
        ),
    ]
