# Generated by Django 5.2.17 on 2026-10-08 07:22

from django.db import migrations, models


def fix_domain(apps, schema_editor):
    """دامنهٔ درست کوتاه‌کننده crpt.ir است (crpt.it مال ما نیست)."""
    S = apps.get_model("affiliate", "AffiliateSettings")
    S.objects.filter(short_domain__in=["crpt.it", "www.crpt.it"]).update(short_domain="crpt.ir")


class Migration(migrations.Migration):

    dependencies = [
        ("affiliate", "0002_tiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliate",
            name="code",
            field=models.CharField(
                help_text="حروف کوچک انگلیسی، عدد و _ (۳ تا ۲۰ حرف)؛ در پیوند کوتاه می\u200cآید: crpt.ir/کد",
                max_length=20,
                unique=True,
                verbose_name="کد پیوند",
            ),
        ),
        migrations.AlterField(
            model_name="affiliatesettings",
            name="short_domain",
            field=models.CharField(
                default="crpt.ir",
                help_text="باید رکورد DNS آن به سرور اشاره کند. خالی: پیوندها با دامنهٔ خود سایت ساخته می\u200cشوند.",
                max_length=60,
                verbose_name="دامنهٔ پیوند کوتاه",
            ),
        ),
        migrations.RunPython(fix_domain, migrations.RunPython.noop),
    ]
