# Generated by Django 5.2.17 on 2026-10-04 13:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorobSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="فید ترب فعال"),
                ),
                (
                    "only_album",
                    models.BooleanField(
                        default=True,
                        help_text="مثل سایت قبلی؛ محصولات بدون آلبوم در ترب نمی\u200cآیند",
                        verbose_name="فقط محصولات دارای آلبوم قیمت",
                    ),
                ),
                (
                    "per_page",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="ترب حداقل ۱۰۰ می\u200cخواهد",
                        verbose_name="تعداد در هر صفحه",
                    ),
                ),
                (
                    "price_divisor",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="برای تبدیل ریال به تومان ۱۰",
                        verbose_name="تقسیم\u200cکنندهٔ قیمت",
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="درصد مالیات افزوده",
                    ),
                ),
                (
                    "decrease_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="درصد کاهش قیمت در ترب",
                    ),
                ),
                (
                    "round_to",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="۰ = بدون گرد کردن",
                        verbose_name="گرد کردن قیمت ترب به",
                    ),
                ),
                (
                    "title_suffix",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="پسوند عنوان"
                    ),
                ),
                (
                    "registry_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="متن رجیستر"
                    ),
                ),
                (
                    "guarantee_attr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نامک ویژگی گارانتی"
                    ),
                ),
                (
                    "excluded",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="محصولات مستثنی از ترب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات فید ترب",
                "verbose_name_plural": "تنظیمات فید ترب",
            },
        ),
    ]
