# Generated by Django 5.2.17 on 2026-10-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torob", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="torobsettings",
            name="emalls_enabled",
            field=models.BooleanField(
                default=True,
                help_text="نشانی برای پنل ایمالز: https://irancarpet.net (همان روش افزونهٔ رسمی ووکامرس ایمالز)",
                verbose_name="فید ایمالز فعال",
            ),
        ),
    ]
