# Generated by Django 5.2.17 on 2026-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to="%Y/%m/", verbose_name="فایل"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=500, verbose_name="عنوان"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="متن جایگزین (alt)"
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="زیرنویس")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "رسانه",
                "verbose_name_plural": "رسانه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="ایران کارپت", max_length=200, verbose_name="نام سایت"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, max_length=300, verbose_name="شعار"),
                ),
                (
                    "title_separator",
                    models.CharField(
                        default="-", max_length=10, verbose_name="جداکنندهٔ عنوان"
                    ),
                ),
                (
                    "home_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان صفحهٔ اصلی"
                    ),
                ),
                (
                    "home_description",
                    models.TextField(blank=True, verbose_name="توضیحات صفحهٔ اصلی"),
                ),
                (
                    "title_templates",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="کلیدها مثل pt_product_title یا tax_product_cat_description (از Rank Math)",
                        verbose_name="قالب عنوان/توضیحات پیش\u200cفرض",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=100, verbose_name="تلفن"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                ("footer_html", models.TextField(blank=True, verbose_name="HTML فوتر")),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
