# Generated by Django 5.2.17 on 2026-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_points",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='فهرست [عنوان، توضیح]؛ مثل [["ارسال رایگان", "برای سفارش\u200cهای بالای ۲۵ میلیون تومان"]]',
                verbose_name="امتیازهای فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="با کد کشور، بدون صفر و +؛ مثل 989121234567",
                max_length=20,
                verbose_name="شمارهٔ واتساپ",
            ),
        ),
    ]
