# Generated by Django 5.2.17 on 2026-10-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="trust_badge",
            field=models.ForeignKey(
                blank=True,
                help_text="تصویر سبک از نماد اعتماد که در پایین همهٔ صفحه\u200cها می\u200cآید و به برگهٔ مجوزها لینک می\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.media",
                verbose_name="تصویر نماد (فوتر)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_html",
            field=models.TextField(
                blank=True,
                help_text="کدی که اینماد داده را کامل اینجا بچسبانید. فقط در برگهٔ مجوزها (/license/) بار می\u200cشود تا سرعت سایت کم نشود.",
                verbose_name="کد نماد اعتماد (اینماد و...)",
            ),
        ),
    ]
