# Generated by Django 5.2.17 on 2026-10-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_license_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="عرض جغرافیایی",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="طول جغرافیایی",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_balad",
            field=models.URLField(blank=True, max_length=400, verbose_name="پیوند بلد"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_google",
            field=models.URLField(
                blank=True, max_length=400, verbose_name="پیوند گوگل\u200cمپ"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="map_neshan",
            field=models.URLField(
                blank=True, max_length=400, verbose_name="پیوند نشان"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_city",
            field=models.CharField(
                blank=True, default="کاشان", max_length=80, verbose_name="شهر"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_close",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت بسته شدن"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_close2",
            field=models.TimeField(
                blank=True, null=True, verbose_name="نوبت عصر: بسته شدن"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_days",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sat-thu", "شنبه تا پنجشنبه"),
                    ("sat-wed", "شنبه تا چهارشنبه"),
                    ("all", "همهٔ روزها"),
                    ("sat-fri", "شنبه تا جمعه"),
                ],
                default="sat-thu",
                max_length=10,
                verbose_name="روزهای کاری",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_hours_note",
            field=models.CharField(
                blank=True,
                help_text="مثل «جمعه\u200cها با هماهنگی تلفنی»",
                max_length=150,
                verbose_name="توضیح ساعت کاری",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_name",
            field=models.CharField(
                blank=True,
                help_text="مثل «فروشگاه فرش ایران کارپت کاشان»",
                max_length=150,
                verbose_name="نام فروشگاه حضوری",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_open",
            field=models.TimeField(blank=True, null=True, verbose_name="ساعت باز شدن"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_open2",
            field=models.TimeField(
                blank=True,
                help_text="اگر ظهر تعطیل است",
                null=True,
                verbose_name="نوبت عصر: باز شدن",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="کد پستی فروشگاه"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="store_province",
            field=models.CharField(
                blank=True, default="اصفهان", max_length=80, verbose_name="استان"
            ),
        ),
    ]
