# Generated by Django 5.2.17 on 2026-10-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="map_balad",
            field=models.URLField(
                blank=True, max_length=1500, verbose_name="پیوند بلد"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="map_google",
            field=models.URLField(
                blank=True, max_length=1500, verbose_name="پیوند گوگل\u200cمپ"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="map_neshan",
            field=models.URLField(
                blank=True, max_length=1500, verbose_name="پیوند نشان"
            ),
        ),
    ]
