# Generated by Django 5.2.17 on 2026-10-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_map_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="aparat",
            field=models.URLField(
                blank=True,
                help_text="مثل https://www.aparat.com/username",
                verbose_name="آپارات",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bale_channel",
            field=models.URLField(
                blank=True,
                help_text="مثل https://ble.ir/username",
                verbose_name="کانال بله",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube",
            field=models.URLField(
                blank=True,
                help_text="مثل https://www.youtube.com/@username",
                verbose_name="یوتیوب",
            ),
        ),
    ]
