# Generated by Django 5.2.17 on 2026-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_more_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="home_about",
            field=models.TextField(
                blank=True,
                help_text="بالای فوتر صفحهٔ اول، بسته\u200cشده نمایش داده می\u200cشود. خالی = تیترها و پاراگراف\u200cهای نوشتاری برگهٔ صفحهٔ اول (بدون جعبه\u200cهای محصول و دسته)، و اگر آن هم نبود «معرفی فروشگاه برای هوش مصنوعی».",
                verbose_name="متن «دربارهٔ ایران کارپت» صفحهٔ اول",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twitter",
            field=models.URLField(
                blank=True,
                help_text="مثل https://x.com/username",
                verbose_name="ایکس (توییتر)",
            ),
        ),
    ]
