# Generated by Django 5.2.17 on 2026-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_twitter_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="facebook",
            field=models.URLField(
                blank=True,
                help_text="مثل https://www.facebook.com/username",
                verbose_name="فیس\u200cبوک",
            ),
        ),
    ]
