# Generated by Django 5.2.17 on 2026-10-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_trust_free_shipping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="trust_points",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='فهرست [عنوان، توضیح]؛ مثل [["ارسال رایگان", "برای سفارش\u200cهای بالای ۵۰ میلیون تومان"]]',
                verbose_name="امتیازهای فروشگاه",
            ),
        ),
    ]
