# Generated by Django 5.2.17 on 2026-10-05 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_filter_attrs"),
        ("finder", "0002_defaults"),
        ("pricing", "0004_price_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان صفحه (H1)"),
                ),
                (
                    "auto",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="ساخت خودکار"
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="خالی بماند تا متن از روی فرش\u200cها و قیمت\u200cها خودکار ساخته شود.",
                        verbose_name="متن بالای صفحه",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="متن پایین صفحه"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان در گوگل"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیح در گوگل"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد فرش"
                    ),
                ),
                (
                    "min_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="کمترین قیمت",
                    ),
                ),
                (
                    "max_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="بیشترین قیمت",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="آخرین به\u200cروزرسانی",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"group": "color"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="finder.need",
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "reeds",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.attributeterm",
                        verbose_name="شانه",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="pricing.size",
                        verbose_name="سایز",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        help_text="مثل «برجسته» یا «سنتی»؛ برای صفحه\u200cهای دستی",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="finder.need",
                        verbose_name="سبک یا جنس (اختیاری)",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحهٔ فرود",
                "verbose_name_plural": "صفحه\u200cهای فرود (سایز، شانه، رنگ)",
                "ordering": ["-count"],
            },
        ),
    ]
