# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        help_text="شناسهٔ گروه mnswmc",
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="نام آلبوم")),
                (
                    "code",
                    models.CharField(max_length=40, unique=True, verbose_name="کد"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="کارخانه / برند"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="قیمت پایه (خرید، تومان)",
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[("fixed", "مبلغ ثابت"), ("percent", "درصدی")],
                        default="fixed",
                        max_length=20,
                        verbose_name="نوع پرتی",
                    ),
                ),
                (
                    "waste_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="مقدار پرتی",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("sort_order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="آخرین تغییر قیمت",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "آلبوم قیمت",
                "verbose_name_plural": "آلبوم\u200cهای قیمت",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15"),
                        max_digits=6,
                        verbose_name="درصد سود فروش",
                    ),
                ),
                (
                    "shipping_fixed",
                    models.PositiveBigIntegerField(
                        default=500000, verbose_name="هزینهٔ حمل ثابت (تومان)"
                    ),
                ),
                (
                    "round_to",
                    models.PositiveIntegerField(
                        default=100000, verbose_name="گرد کردن به (تومان)"
                    ),
                ),
                (
                    "round_method",
                    models.CharField(
                        choices=[("up", "رو به بالا"), ("nearest", "نزدیک\u200cترین")],
                        default="up",
                        max_length=10,
                        verbose_name="روش گرد کردن",
                    ),
                ),
                (
                    "show_size_table",
                    models.BooleanField(
                        default=True,
                        verbose_name="نمایش جدول قیمت سایزها در صفحهٔ محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات قیمت\u200cگذاری",
                "verbose_name_plural": "تنظیمات قیمت\u200cگذاری",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=64, unique=True, verbose_name="نامک"),
                ),
                ("label", models.CharField(max_length=160, verbose_name="عنوان")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rect", "مستطیل"),
                            ("runner", "کناره"),
                            ("rug", "قالیچه"),
                            ("doormat", "پادری / رویه\u200cپشتی"),
                            ("round", "گرد"),
                            ("custom", "سفارشی / برشی"),
                        ],
                        default="rect",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="عرض (متر)",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="طول (متر)",
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="قطر (متر)",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="برای گرد: قطر²",
                        max_digits=10,
                        verbose_name="مساحت (m²)",
                    ),
                ),
                (
                    "default_pair_only",
                    models.BooleanField(
                        default=False, verbose_name="پیش\u200cفرض فقط زوج"
                    ),
                ),
                (
                    "needs_waste",
                    models.BooleanField(
                        default=False,
                        help_text="فقط ۹ متری مستطیل",
                        verbose_name="هزینهٔ پرتی دارد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("sort_order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "legacy_slugs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="نامک\u200cهای pa_carpet-size که به این سایز نگاشت می\u200cشوند (برای ایمپورت)",
                        verbose_name="نامک\u200cهای قدیمی وردپرس",
                    ),
                ),
            ],
            options={
                "verbose_name": "سایز",
                "verbose_name_plural": "سایزها",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PriceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "new_price",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=120)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="pricing.album",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ قیمت",
                "verbose_name_plural": "لاگ تغییرات قیمت",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="album",
            name="base_size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="pricing.size",
                verbose_name="سایز پایه",
            ),
        ),
    ]
