# Generated by Django 5.2.17 on 2026-10-04 13:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="even_sizes",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="pricing.size",
                verbose_name="سایزهای فقط زوج",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="profit_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15"),
                max_digits=6,
                verbose_name="درصد سود",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="round_to",
            field=models.PositiveIntegerField(
                default=10000,
                help_text="رو به بالا",
                verbose_name="گرد کردن به (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="shipping_fixed",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="به قیمت ۱۲ متری اضافه می\u200cشود و برای بقیهٔ سایزها به نسبت متراژ",
                verbose_name="هزینهٔ ارسال (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="sizes",
            field=models.ManyToManyField(
                blank=True,
                help_text="مشتری همین سایزها را برای محصولات این آلبوم می\u200cبیند",
                related_name="albums",
                to="pricing.size",
                verbose_name="سایزهای آلبوم",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name="قیمت خرید ۱۲ متری (تومان)",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="waste_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="فقط برای سایزهای «با پرتی» (۹ متری ۲٫۵×۳٫۵)، روی قیمت فروش",
                max_digits=20,
                verbose_name="مقدار پرتی",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="wp_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                help_text="شناسهٔ آلبوم در وردپرس",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingsettings",
            name="markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15"),
                max_digits=6,
                verbose_name="درصد سود پیش\u200cفرض آلبوم تازه",
            ),
        ),
        migrations.AlterField(
            model_name="pricingsettings",
            name="round_to",
            field=models.PositiveIntegerField(
                default=10000, verbose_name="گرد کردن پیش\u200cفرض آلبوم تازه (تومان)"
            ),
        ),
        migrations.AlterField(
            model_name="pricingsettings",
            name="shipping_fixed",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="هزینهٔ ارسال پیش\u200cفرض آلبوم تازه (تومان)"
            ),
        ),
    ]
