# Generated by Django 5.2.17 on 2026-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_album_plugin_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="خالی بگذارید تا خودکار ساخته شود",
                max_length=40,
                unique=True,
                verbose_name="کد",
            ),
        ),
    ]
