# Generated by Django 5.2.17 on 2026-10-04 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_auto_codes"),
        ("core", "0002_contact_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latest_version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="آخرین نسخه"
                    ),
                ),
                (
                    "min_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="نسخه\u200cهای پایین\u200cتر مجبور به به\u200cروزرسانی می\u200cشوند",
                        max_length=20,
                        verbose_name="کمترین نسخهٔ قابل استفاده",
                    ),
                ),
                (
                    "update_url",
                    models.CharField(
                        blank=True,
                        help_text="صفحهٔ اپ در کافه\u200cبازار",
                        max_length=300,
                        verbose_name="لینک دریافت اپ",
                    ),
                ),
                (
                    "update_note",
                    models.TextField(blank=True, verbose_name="توضیح نسخهٔ تازه"),
                ),
                (
                    "home_notice",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="پیام بالای صفحهٔ اول اپ",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات اپلیکیشن",
                "verbose_name_plural": "تنظیمات اپلیکیشن",
            },
        ),
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                (
                    "device",
                    models.CharField(blank=True, max_length=150, verbose_name="دستگاه"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "توکن اپ",
                "verbose_name_plural": "توکن\u200cهای اپ",
            },
        ),
        migrations.CreateModel(
            name="AppNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                ("body", models.CharField(max_length=300, verbose_name="متن")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deal", "تخفیف"),
                            ("new", "فرش تازه"),
                            ("news", "خبر"),
                        ],
                        default="news",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="اگر محصول یا دسته انتخاب نشده",
                        max_length=300,
                        verbose_name="پیوند",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="زمان ارسال",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.category",
                        verbose_name="دسته",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.media",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان اپ",
                "verbose_name_plural": "اعلان\u200cهای اپ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("install_id", models.CharField(max_length=64, unique=True)),
                ("platform", models.CharField(default="android", max_length=20)),
                ("app_version", models.CharField(blank=True, max_length=20)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "دستگاه",
                "verbose_name_plural": "دستگاه\u200cهای نصب\u200cشده",
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه\u200cمندی",
                "verbose_name_plural": "علاقه\u200cمندی\u200cها",
                "unique_together": {("user", "product")},
            },
        ),
    ]
