# Generated by Django 5.2.17 on 2026-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("path", models.CharField(max_length=255)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
                ("entries", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DailyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("product_id", models.PositiveIntegerField(db_index=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
                ("carts", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("src", models.CharField(max_length=10)),
                ("src_name", models.CharField(blank=True, max_length=60)),
                ("medium", models.CharField(blank=True, max_length=40)),
                ("utm_campaign", models.CharField(blank=True, max_length=80)),
                ("campaign_id", models.PositiveIntegerField(db_index=True, default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
                ("carts", models.PositiveIntegerField(default=0)),
                ("orders", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DailyTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("visitors", models.PositiveIntegerField(default=0)),
                ("new_visitors", models.PositiveIntegerField(default=0)),
                ("mobile", models.PositiveIntegerField(default=0)),
                ("carts", models.PositiveIntegerField(default=0)),
                ("orders", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RolledDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True)),
                ("done_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField()),
                ("day", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("v", "بازدید صفحه"),
                            ("c", "افزودن به سبد"),
                            ("o", "ثبت سفارش"),
                        ],
                        default="v",
                        max_length=1,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=255)),
                ("product_id", models.PositiveIntegerField(blank=True, null=True)),
                ("visitor", models.CharField(max_length=16)),
                ("entry", models.BooleanField(default=False)),
                ("new", models.BooleanField(default=False)),
                ("src", models.CharField(default="direct", max_length=10)),
                ("src_name", models.CharField(blank=True, max_length=60)),
                ("medium", models.CharField(blank=True, max_length=40)),
                ("utm_campaign", models.CharField(blank=True, max_length=80)),
                ("campaign_id", models.PositiveIntegerField(blank=True, null=True)),
                ("link_id", models.PositiveIntegerField(blank=True, null=True)),
                ("device", models.CharField(default="d", max_length=1)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["day", "kind"], name="stats_hit_day_5ae7d8_idx"
                    ),
                    models.Index(
                        fields=["campaign_id", "day"],
                        name="stats_hit_campaig_569f48_idx",
                    ),
                    models.Index(
                        fields=["product_id", "day"],
                        name="stats_hit_product_fba72e_idx",
                    ),
                ],
            },
        ),
    ]
