# Generated by Django 5.2.17 on 2026-10-08 07:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0011_product_review_note_product_review_status"),
        ("core", "0011_facebook"),
        ("shop", "0008_offer_no_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="فروش فروشندگان فعال است"
                    ),
                ),
                (
                    "signup_open",
                    models.BooleanField(
                        default=True, verbose_name="ثبت\u200cنام فروشندهٔ تازه باز است"
                    ),
                ),
                (
                    "default_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="درصدی از مبلغ کالا که سهم ایران کارپت است؛ برای هر دسته یا هر فروشنده جدا هم می\u200cشود گذاشت.",
                        max_digits=5,
                        verbose_name="کمیسیون پیش\u200cفرض (درصد)",
                    ),
                ),
                (
                    "accept_hours",
                    models.PositiveSmallIntegerField(
                        default=24, verbose_name="مهلت پذیرش سفارش (ساعت)"
                    ),
                ),
                (
                    "auto_deliver_days",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="اگر مشتری یا مدیر «تحویل شد» را نزد، این\u200cقدر بعد از ثبت کد رهگیری تحویل\u200cشده حساب می\u200cشود.",
                        verbose_name="تحویل خودکار پس از ارسال (روز)",
                    ),
                ),
                (
                    "hold_days",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="مهلت مرجوعی قبل از تسویه (روز)"
                    ),
                ),
                (
                    "min_payout",
                    models.PositiveBigIntegerField(
                        default=1000000, verbose_name="حداقل مبلغ تسویه (تومان)"
                    ),
                ),
                (
                    "terms",
                    models.TextField(
                        default="- فقط کالای اصل و نو، با عکس واقعی و مشخصات درست ثبت کنید؛ کالای تقلبی یا متفاوت با عکس، با مرجوعی و توقف حساب همراه است.\n- قیمت هر کالا را خودتان تعیین می\u200cکنید و باید با قیمت فروش شما در جاهای دیگر هم\u200cخوان باشد.\n- سفارش تازه را حداکثر ظرف {پذیرش} ساعت تأیید و در زمان آماده\u200cسازی اعلام\u200cشده ارسال کنید و کد رهگیری را ثبت کنید.\n- اگر کالایی تمام شد، همان لحظه موجودی\u200cاش را صفر کنید؛ لغو سفارش از طرف فروشنده در امتیاز فروشگاه اثر دارد.\n- مبلغ هر سفارش (منهای کمیسیون) {مرجوعی} روز بعد از تحویل به مشتری، به شماره شبای ثبت\u200cشده به نام خودتان واریز می\u200cشود.\n- ارتباط با مشتری و پاسخ به پیام\u200cها از طریق ایران کارپت است؛ گرفتن پول یا سفارش خارج از سایت ممنوع است.",
                        help_text="هر خط یک بند. {پذیرش} = مهلت پذیرش، {مرجوعی} = مهلت مرجوعی",
                        verbose_name="قوانین فروشندگان",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات مارکت\u200cپلیس",
                "verbose_name_plural": "تنظیمات مارکت\u200cپلیس",
            },
        ),
        migrations.CreateModel(
            name="CategoryCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="کمیسیون (درصد)"
                    ),
                ),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_commission",
                        to="catalog.category",
                        verbose_name="دسته",
                    ),
                ),
            ],
            options={
                "verbose_name": "کمیسیون دسته",
                "verbose_name_plural": "کمیسیون دسته\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تأیید"),
                            ("active", "فعال"),
                            ("paused", "تعطیل موقت (به خواست فروشنده)"),
                            ("suspended", "متوقف"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="نام فروشگاه"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=60,
                        unique=True,
                        verbose_name="نشانی فروشگاه",
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="دربارهٔ فروشگاه")),
                (
                    "kind",
                    models.CharField(
                        choices=[("person", "حقیقی"), ("company", "حقوقی (شرکت)")],
                        default="person",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        max_length=120, verbose_name="نام صاحب فروشگاه / مدیرعامل"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        verbose_name="کد ملی / شناسهٔ ملی شرکت",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تلفن ثابت"
                    ),
                ),
                (
                    "province",
                    models.CharField(blank=True, max_length=60, verbose_name="استان"),
                ),
                ("city", models.CharField(max_length=80, verbose_name="شهر ارسال")),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="نشانی انبار / فروشگاه"),
                ),
                (
                    "shipping",
                    models.CharField(
                        choices=[
                            ("cod", "پس\u200cکرایه (هزینه با مشتری)"),
                            ("free", "ارسال رایگان"),
                        ],
                        default="cod",
                        max_length=6,
                        verbose_name="هزینهٔ ارسال",
                    ),
                ),
                (
                    "prep_days",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="زمان آماده\u200cسازی (روز کاری)"
                    ),
                ),
                (
                    "return_policy",
                    models.CharField(
                        blank=True,
                        default="تا ۷ روز پس از تحویل، در صورت مغایرت با مشخصات یا ایراد تولید",
                        max_length=300,
                        verbose_name="شرایط مرجوعی",
                    ),
                ),
                (
                    "sheba",
                    models.CharField(
                        blank=True, max_length=26, verbose_name="شماره شبا"
                    ),
                ),
                (
                    "account_holder",
                    models.CharField(blank=True, max_length=120, verbose_name="به نام"),
                ),
                (
                    "commission_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اگر پر باشد، به\u200cجای کمیسیون دسته\u200cها برای همهٔ کالاهای این فروشنده حساب می\u200cشود.",
                        max_digits=5,
                        null=True,
                        verbose_name="کمیسیون اختصاصی (درصد)",
                    ),
                ),
                (
                    "trusted",
                    models.BooleanField(
                        default=False,
                        help_text="روشن: کالاها و ویرایش\u200cهایش بدون بررسی منتشر می\u200cشود.",
                        verbose_name="فروشندهٔ مورد اعتماد",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ ثبت\u200cنام",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.media",
                        verbose_name="لوگو",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "فروشنده",
                "verbose_name_plural": "فروشندگان",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="کد پیگیری واریز"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="توضیح"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ واریز"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="market.seller",
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسویهٔ فروشنده",
                "verbose_name_plural": "تسویهٔ فروشندگان",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "منتظر پرداخت مشتری"),
                            ("new", "سفارش تازه"),
                            ("accepted", "در حال آماده\u200cسازی"),
                            ("shipped", "ارسال شد"),
                            ("delivered", "تحویل شد"),
                            ("cancelled", "لغو شد"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "items_total",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مبلغ کالاها (تومان)"
                    ),
                ),
                (
                    "commission",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="کمیسیون ایران کارپت (تومان)"
                    ),
                ),
                (
                    "seller_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="سهم فروشنده (تومان)"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="شرکت حمل"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد رهگیری ارسال"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="دلیل لغو"
                    ),
                ),
                (
                    "settle",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("payable", "قابل تسویه"),
                            ("paid", "تسویه شد"),
                            ("none", "بدون تسویه"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=8,
                        verbose_name="تسویه",
                    ),
                ),
                ("stock_taken", models.BooleanField(default=False, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پرداخت مشتری"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پذیرش"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ارسال"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="تحویل"),
                ),
                (
                    "payable_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="قابل تسویه از"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_orders",
                        to="shop.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="market.seller",
                        verbose_name="فروشنده",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="market.sellerpayout",
                        verbose_name="تسویه",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش فروشنده",
                "verbose_name_plural": "سفارش\u200cهای فروشندگان",
                "ordering": ["-created_at"],
                "unique_together": {("order", "seller")},
            },
        ),
    ]
