# Generated by Django 5.2.17 on 2026-10-04 21:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cheque", "چک صیادی"),
                            ("beta", "سامانهٔ بتا (بانک رفاه)"),
                            ("other", "سایر"),
                        ],
                        default="cheque",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «۵۰٪ پیش\u200cپرداخت، بقیه تا ۱۲ ماه با چک صیادی»",
                        max_length=200,
                        verbose_name="خلاصه (یک خط)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("sort_order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "monthly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("6"),
                        help_text="سود با راس\u200cگیری: درصد ماهانه × (میانگین روزهای سررسید ÷ ۳۰)",
                        max_digits=5,
                        verbose_name="سود ماهانه (درصد)",
                    ),
                ),
                (
                    "min_down_percent",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="حداقل پیش\u200cپرداخت (٪)"
                    ),
                ),
                (
                    "max_down_percent",
                    models.PositiveSmallIntegerField(
                        default=90, verbose_name="حداکثر پیش\u200cپرداخت (٪)"
                    ),
                ),
                (
                    "down_step",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="گام انتخاب پیش\u200cپرداخت (٪)"
                    ),
                ),
                (
                    "min_months",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="کمترین مدت (ماه)"
                    ),
                ),
                (
                    "max_months",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="بیشترین مدت (ماه)"
                    ),
                ),
                (
                    "allow_monthly",
                    models.BooleanField(default=True, verbose_name="قسط ماهانه"),
                ),
                (
                    "allow_bimonthly",
                    models.BooleanField(
                        default=True, verbose_name="قسط دوماه\u200cیک\u200cبار"
                    ),
                ),
                (
                    "first_due_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="زمان آماده\u200cشدن فرش؛ تاریخ اولین قسط = این روز + یک دوره",
                        verbose_name="شروع اقساط چند روز بعد از ثبت سفارش",
                    ),
                ),
                (
                    "round_to",
                    models.PositiveIntegerField(
                        default=100000,
                        help_text="رو به بالا",
                        verbose_name="گرد کردن مبلغ هر قسط به (تومان)",
                    ),
                ),
                (
                    "min_order_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="حداقل مبلغ سبد (تومان)"
                    ),
                ),
                (
                    "down_timing",
                    models.CharField(
                        choices=[
                            ("checkout", "همان موقع ثبت سفارش (آنلاین)"),
                            ("approval", "بعد از تأیید مدارک (آنلاین)"),
                        ],
                        default="checkout",
                        max_length=10,
                        verbose_name="زمان پرداخت پیش\u200cپرداخت",
                    ),
                ),
                (
                    "ask_holder_name",
                    models.BooleanField(
                        default=True,
                        verbose_name="نام و نام خانوادگی (صاحب چک / بازنشسته)",
                    ),
                ),
                (
                    "ask_national_code",
                    models.BooleanField(default=True, verbose_name="کد ملی"),
                ),
                (
                    "ask_cheque_image",
                    models.BooleanField(default=False, verbose_name="تصویر یک برگ چک"),
                ),
                (
                    "ask_sayad_id",
                    models.BooleanField(
                        default=False, verbose_name="شناسهٔ صیادی چک (۱۶ رقم)"
                    ),
                ),
                (
                    "ask_bank_name",
                    models.BooleanField(default=False, verbose_name="نام بانک"),
                ),
                (
                    "ask_pensioner_type",
                    models.BooleanField(
                        default=False, verbose_name="بازنشسته یا مستمری\u200cبگیر"
                    ),
                ),
                (
                    "ask_retiree_id",
                    models.BooleanField(
                        default=False, verbose_name="شمارهٔ بازنشستگی / مستمری"
                    ),
                ),
                (
                    "ask_sms_mobile",
                    models.BooleanField(
                        default=False,
                        verbose_name="موبایلی که پیامک بانک به آن می\u200cرود",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="در صفحهٔ خرید اقساطی و تسویه حساب",
                        verbose_name="شرایط و توضیحات",
                    ),
                ),
                (
                    "submit_note",
                    models.TextField(
                        blank=True,
                        help_text="مثلاً «تصویر واضح یک برگ چک، بدون نوشتن مبلغ و تاریخ»",
                        verbose_name="راهنمای کنار فرم مدارک",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        help_text="در صفحهٔ سفارش، تا وقتی درخواست بررسی نشده",
                        verbose_name="پیام بعد از ثبت درخواست",
                    ),
                ),
                (
                    "approved_note",
                    models.TextField(
                        blank=True,
                        help_text="در صفحهٔ سفارش بعد از تأیید؛ مثلاً نحوهٔ نوشتن چک\u200cها و نشانی پست",
                        verbose_name="پیام بعد از تأیید",
                    ),
                ),
                (
                    "approved_sms",
                    models.TextField(
                        blank=True,
                        help_text="متغیرها: {name} {order} {link} — برای ارسال، «شمارهٔ خط پیامک گروهی» در تنظیمات پیامک لازم است",
                        verbose_name="پیامک تأیید به مشتری",
                    ),
                ),
                (
                    "rejected_sms",
                    models.TextField(
                        blank=True,
                        help_text="متغیرها: {name} {order}",
                        verbose_name="پیامک رد درخواست",
                    ),
                ),
            ],
            options={
                "verbose_name": "روش اقساط",
                "verbose_name_plural": "روش\u200cهای اقساط",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
