# Generated by Django 5.2.17 on 2026-10-04 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "افزودن"),
                            ("update", "ویرایش"),
                            ("delete", "حذف"),
                            ("action", "عملیات"),
                        ],
                        max_length=10,
                    ),
                ),
                ("section", models.CharField(max_length=100, verbose_name="بخش")),
                ("object_id", models.CharField(blank=True, max_length=50)),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=300, verbose_name="مورد"),
                ),
                (
                    "detail",
                    models.CharField(blank=True, max_length=500, verbose_name="جزئیات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالیت",
                "verbose_name_plural": "گزارش فعالیت",
                "ordering": ["-created_at"],
            },
        ),
    ]
