# Generated by Django 5.2.17 on 2026-10-04 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(db_index=True, max_length=11)),
                ("code_hash", models.CharField(max_length=128)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("used", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "کد یک\u200cبارمصرف",
                "verbose_name_plural": "کدهای یک\u200cبارمصرف",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="موبایل",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "province",
                    models.CharField(blank=True, max_length=60, verbose_name="استان"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="شهر"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="کد پستی"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل مشتری",
                "verbose_name_plural": "پروفایل مشتریان",
            },
        ),
    ]
