# Generated by Django 5.2.17 on 2026-10-04 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=120, verbose_name="عنوان (برای خودتان)"
                    ),
                ),
                ("text", models.TextField(verbose_name="متن پیامک")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "همهٔ مشتری\u200cهای دارای موبایل"),
                            ("buyers", "مشتری\u200cهایی که سفارش داده\u200cاند"),
                            ("custom", "شماره\u200cهای دلخواه"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="گیرنده\u200cها",
                    ),
                ),
                (
                    "custom_numbers",
                    models.TextField(
                        blank=True,
                        help_text="هر شماره در یک خط",
                        verbose_name="شماره\u200cهای دلخواه",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("sending", "در حال ارسال"),
                            ("done", "ارسال شد"),
                            ("failed", "متوقف شد"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد گیرنده"),
                ),
                (
                    "sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ارسال\u200cشده"
                    ),
                ),
                (
                    "failed",
                    models.PositiveIntegerField(default=0, verbose_name="ناموفق"),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="آخرین خطا"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ساخته شده"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان ارسال"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیامک گروهی",
                "verbose_name_plural": "پیامک\u200cهای گروهی",
                "ordering": ["-created_at"],
            },
        ),
    ]
