# Generated by Django 5.2.17 on 2026-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sms_campaigns"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="روز تولد"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_month",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="ماه تولد (شمسی)"
            ),
        ),
    ]
