# Generated by Django 5.2.17 on 2026-10-05 20:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_reviews_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="RajyarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="اتصال فعال باشد"),
                ),
                (
                    "url",
                    models.URLField(
                        default="https://rajyar.ir/api/v1/",
                        verbose_name="نشانی API رج\u200cیار",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="در رج\u200cیار ← کلیدهای API ساخته می\u200cشود؛ مثل rjy_…",
                        max_length=200,
                        verbose_name="کلید API",
                    ),
                ),
                (
                    "channels",
                    models.CharField(
                        blank=True,
                        help_text="شناسهٔ کانال\u200cهای رج\u200cیار با ویرگول، مثل 2 یا 2,5. فهرست کانال\u200cها بعد از «بررسی اتصال» کنار صفحه دیده می\u200cشود. تا خالی است چیزی فرستاده نمی\u200cشود (تا محصولات به کانال\u200cهای دیگرِ این کلید نروند).",
                        max_length=200,
                        verbose_name="کانال\u200cها",
                    ),
                ),
                (
                    "auto_new",
                    models.BooleanField(
                        default=False,
                        help_text="هر محصولی که برای اولین بار منتشر شود و عکس داشته باشد، به کانال\u200cها می\u200cرود.",
                        verbose_name="فرش\u200cهای تازه خودکار فرستاده شوند",
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                        verbose_name="فاصلهٔ بین پست\u200cها در ارسال گروهی (دقیقه)",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="فرش ماشینی، فرش کاشان، ایران کارپت",
                        help_text="با ویرگول؛ در کانال\u200cهایی که هشتگ روشن است، هشتگ می\u200cشوند.",
                        max_length=200,
                        verbose_name="برچسب\u200cهای ثابت",
                    ),
                ),
                (
                    "footer",
                    models.CharField(
                        blank=True,
                        default="خرید نقدی و اقساطی، ارسال مستقیم از کاشان",
                        max_length=200,
                        verbose_name="خط پایانی پست",
                    ),
                ),
                (
                    "channels_cache",
                    models.JSONField(
                        blank=True,
                        default=list,
                        editable=False,
                        verbose_name="کانال\u200cهای مجاز (از آخرین بررسی)",
                    ),
                ),
                (
                    "last_check",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=300,
                        verbose_name="نتیجهٔ آخرین بررسی",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات رج\u200cیار",
                "verbose_name_plural": "تنظیمات رج\u200cیار",
            },
        ),
        migrations.CreateModel(
            name="RajyarPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remote_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه در رج\u200cیار"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "فرستاده شد"),
                            ("scheduled", "در صف انتشار"),
                            ("published", "منتشر شد"),
                            ("partial", "بخشی منتشر شد"),
                            ("failed", "خطا"),
                            ("cancelled", "لغو شد"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "links",
                    models.JSONField(
                        blank=True, default=list, verbose_name="پیوند پیام\u200cها"
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="زمان ارسال",
                    ),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rajyar_posts",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارسال به کانال",
                "verbose_name_plural": "ارسال\u200cها به کانال\u200cها (رج\u200cیار)",
                "ordering": ["-created_at"],
            },
        ),
    ]
