# Generated by Django 5.2.17 on 2026-10-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_price_list"),
        ("rajyar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rajyarsettings",
            name="button_text",
            field=models.CharField(
                blank=True,
                default="مشاهده و خرید",
                help_text="در پیام\u200cرسان\u200cهایی که دکمهٔ شیشه\u200cای دارند دکمه می\u200cشود؛ در بقیه پیوند متنی.",
                max_length=40,
                verbose_name="متن دکمه/پیوند",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="price_mode",
            field=models.CharField(
                choices=[
                    ("none", "قیمت نیاید"),
                    ("sizes", "قیمت سایزهای انتخاب\u200cشده"),
                    ("from", "فقط «قیمت از …»"),
                ],
                default="sizes",
                max_length=10,
                verbose_name="قیمت در پست",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="price_sizes",
            field=models.ManyToManyField(
                blank=True,
                help_text="خالی = بزرگ\u200cترین دو سایز موجود هر فرش. قیمت همیشه با تاریخ روز انتشار می\u200cآید.",
                related_name="+",
                to="pricing.size",
                verbose_name="سایزهای قیمت",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="show_specs",
            field=models.BooleanField(
                default=True, verbose_name="مشخصات (شانه، تراکم، جنس نخ، رنگ) بیاید"
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="show_summary",
            field=models.BooleanField(
                default=False, verbose_name="توضیح کوتاه محصول هم بیاید"
            ),
        ),
    ]
