# Generated by Django 5.2.17 on 2026-10-06 07:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_fill_design"),
        ("pricing", "0004_price_list"),
        ("rajyar", "0002_post_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="rajyarpost",
            name="image",
            field=models.CharField(blank=True, max_length=300, verbose_name="تصویر"),
        ),
        migrations.AddField(
            model_name="rajyarpost",
            name="kind",
            field=models.CharField(
                choices=[
                    ("product", "فرش (دستی یا فرش تازه)"),
                    ("daily", "فرش روزانه"),
                    ("weekly", "لیست قیمت هفتگی"),
                ],
                db_index=True,
                default="product",
                max_length=10,
                verbose_name="نوع",
            ),
        ),
        migrations.AddField(
            model_name="rajyarpost",
            name="slot",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="نوبت خودکار",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="daily_albums",
            field=models.ManyToManyField(
                blank=True,
                help_text="خالی = همهٔ فرش\u200cهای موجود و عکس\u200cدار",
                related_name="+",
                to="pricing.album",
                verbose_name="فقط از آلبوم\u200cهای",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="daily_enabled",
            field=models.BooleanField(
                default=False, verbose_name="هر روز چند فرش تصادفی فرستاده شود"
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="daily_times",
            field=models.CharField(
                default="10:00, 17:00, 21:00",
                help_text="با ویرگول؛ پیش\u200cفرض صبح، عصر و شب. هر فرش تا وقتی همهٔ فرش\u200cها یک بار نرفته\u200cاند تکرار نمی\u200cشود.",
                max_length=60,
                verbose_name="ساعت\u200cهای ارسال روزانه",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_albums",
            field=models.ManyToManyField(
                blank=True,
                help_text="خالی = همهٔ آلبوم\u200cهایی که در لیست قیمت سایت هستند.",
                related_name="+",
                to="pricing.album",
                verbose_name="آلبوم\u200cهای لیست قیمت",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "شنبه"),
                    (6, "یکشنبه"),
                    (0, "دوشنبه"),
                    (1, "سه\u200cشنبه"),
                    (2, "چهارشنبه"),
                    (3, "پنجشنبه"),
                    (4, "جمعه"),
                ],
                default=5,
                verbose_name="روز ارسال",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_enabled",
            field=models.BooleanField(
                default=False, verbose_name="لیست قیمت هفتگی (تصویری) فرستاده شود"
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_sizes",
            field=models.ManyToManyField(
                blank=True,
                help_text="پیش\u200cفرض ۱۲، ۹ و ۶ متری. برای هر آلبوم، میانگین قیمت فرش\u200cهای آن در این سایزها می\u200cآید.",
                related_name="+",
                to="pricing.size",
                verbose_name="سایزهای لیست قیمت",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_time",
            field=models.TimeField(
                default=datetime.time(10, 0), verbose_name="ساعت ارسال"
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_title",
            field=models.CharField(
                default="قیمت روز فرش ماشینی کاشان",
                max_length=80,
                verbose_name="عنوان تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="rajyarpost",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rajyar_posts",
                to="catalog.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="rajyarsettings",
            name="footer",
            field=models.TextField(
                blank=True,
                default="✅ خرید نقدی و اقساطی، ارسال مستقیم از کاشان\n📞 {تلفن}\n{کانال\u200cها}",
                help_text="هر خط یک خط پست. {کانال\u200cها} = نشانی کانال\u200cها و صفحه\u200cهای فروشگاه از «تنظیمات ← سایت و تماس» (تلگرام، ایتا، بله، اینستاگرام، آپارات، یوتیوب…)، {تلفن}، {موبایل} و {سایت}. خالی = بدون خط پایانی.",
                verbose_name="پایان همهٔ پست\u200cها",
            ),
        ),
    ]
