# Generated by Django 5.2.17 on 2026-10-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_price_list"),
        ("rajyar", "0004_auto_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_group",
            field=models.CharField(
                choices=[
                    ("reeds", "بر اساس شانه و جنس نخ (میانگین همهٔ آلبوم\u200cها)"),
                    ("album", "هر آلبوم یک ردیف"),
                ],
                default="reeds",
                max_length=10,
                verbose_name="ردیف\u200cهای لیست قیمت",
            ),
        ),
        migrations.AddField(
            model_name="rajyarsettings",
            name="weekly_reeds",
            field=models.CharField(
                blank=True,
                default="700, 1000, 1200, 1500",
                help_text="با ویرگول؛ خالی = همهٔ شانه\u200cها. هر شانه با جنس نخش جدا می\u200cآید، مثل «۷۰۰ شانه پلی\u200cاستر» و «۷۰۰ شانه آکریلیک».",
                max_length=60,
                verbose_name="شانه\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="rajyarsettings",
            name="weekly_albums",
            field=models.ManyToManyField(
                blank=True,
                help_text="خالی = همهٔ آلبوم\u200cها (در حالت «هر آلبوم یک ردیف»: آلبوم\u200cهای لیست قیمت سایت).",
                related_name="+",
                to="pricing.album",
                verbose_name="فقط از آلبوم\u200cهای",
            ),
        ),
    ]
