# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "برچسب مقاله",
                "verbose_name_plural": "برچسب\u200cهای مقاله",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="پرسش")),
                ("answer", models.TextField(verbose_name="پاسخ (HTML)")),
                (
                    "group",
                    models.CharField(blank=True, max_length=100, verbose_name="گروه"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "پرسش متداول",
                "verbose_name_plural": "پرسش\u200cهای متداول",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=255, verbose_name="نامک"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="متن (HTML)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("publish", "منتشرشده"),
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("private", "خصوصی"),
                        ],
                        default="publish",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        help_text="home, shop, cart, contact و...",
                        max_length=50,
                        verbose_name="قالب ویژه",
                    ),
                ),
                ("menu_order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="آخرین ویرایش"
                    ),
                ),
            ],
            options={
                "verbose_name": "برگه",
                "verbose_name_plural": "برگه\u200cها",
                "ordering": ["menu_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="متن (HTML)")),
                ("excerpt", models.TextField(blank=True, verbose_name="خلاصه")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("publish", "منتشرشده"),
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار بررسی"),
                            ("private", "خصوصی"),
                        ],
                        db_index=True,
                        default="publish",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نویسنده"
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="بازدید"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="آخرین ویرایش"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=255, verbose_name="نامک"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "دستهٔ مقاله",
                "verbose_name_plural": "دسته\u200cهای مقاله",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("author_name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "author_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("content", models.TextField(verbose_name="متن")),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="تأییدشده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "دیدگاه",
                "verbose_name_plural": "دیدگاه\u200cها",
                "ordering": ["created_at"],
            },
        ),
    ]
