# Generated by Django 5.2.17 on 2026-10-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_neutral_competitor_titles"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostRewrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=9999,
                        help_text="عدد کمتر زودتر",
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "kind",
                    models.CharField(blank=True, max_length=20, verbose_name="نوع"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=150, verbose_name="چرا"),
                ),
                (
                    "keyword",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="کلمهٔ هدف"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "در صف نوشتن"),
                            ("ready", "آماده (در مهلت بررسی)"),
                            ("approved", "تأیید شد؛ انتشار در نوبت بعدی"),
                            ("published", "منتشر شد"),
                            ("rejected", "رد شد"),
                            ("skipped", "کنار گذاشته شد"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "gsc_clicks",
                    models.PositiveIntegerField(default=0, verbose_name="کلیک گوگل"),
                ),
                (
                    "gsc_impressions",
                    models.PositiveIntegerField(default=0, verbose_name="نمایش گوگل"),
                ),
                (
                    "gsc_position",
                    models.FloatField(default=0, verbose_name="رتبهٔ میانگین"),
                ),
                (
                    "gsc_after",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="آمار گوگل بعد از انتشار"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان تازه"
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو تازه"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیح متای تازه"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="خلاصهٔ تازه")),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="متن تازه (HTML)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت نویسنده")),
                ("warnings", models.TextField(blank=True, verbose_name="هشدارها")),
                (
                    "source_sha",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آماده شد"
                    ),
                ),
                (
                    "publish_after",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انتشار از"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="منتشر شد"
                    ),
                ),
                (
                    "old",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        verbose_name="نسخهٔ قبلی",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewrite",
                        to="blog.post",
                        verbose_name="مقاله",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازنویسی مقاله",
                "verbose_name_plural": "برنامهٔ بازنویسی مقاله\u200cها",
                "ordering": ["rank"],
            },
        ),
    ]
