# Generated by Django 5.2.17 on 2026-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_postrewrite"),
    ]

    operations = [
        migrations.AddField(
            model_name="postrewrite",
            name="merge_into",
            field=models.CharField(
                blank=True,
                help_text="نشانی مقالهٔ اصلی؛ این مقاله با ریدایرکت ۳۰۱ به آن می\u200cرود",
                max_length=300,
                verbose_name="ادغام در",
            ),
        ),
        migrations.AlterField(
            model_name="postrewrite",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "در صف نوشتن"),
                    ("ready", "آماده (در مهلت بررسی)"),
                    ("approved", "تأیید شد؛ انتشار در نوبت بعدی"),
                    ("published", "منتشر شد"),
                    ("rejected", "رد شد"),
                    ("skipped", "کنار گذاشته شد"),
                    ("merged", "ادغام شد (ریدایرکت)"),
                ],
                db_index=True,
                default="queued",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
    ]
