# Generated by Django 5.2.17 on 2026-10-05 12:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_reviews_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=200, verbose_name="جستجو")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "سایت"),
                            ("app", "اپ"),
                            ("finder", "فرش\u200cیاب"),
                        ],
                        max_length=10,
                        verbose_name="کجا",
                    ),
                ),
                ("hits", models.PositiveIntegerField(default=1, verbose_name="دفعات")),
                (
                    "results",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد نتیجه (آخرین بار)"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="اولین بار"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="آخرین بار",
                    ),
                ),
            ],
            options={
                "verbose_name": "جستجوی مشتری",
                "verbose_name_plural": "جستجوهای مشتری\u200cها",
                "ordering": ["-hits"],
                "unique_together": {("query", "source")},
            },
        ),
        migrations.CreateModel(
            name="ProductAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("stock", "موجود شد خبرم کن"),
                            ("price", "ارزان شد خبرم کن"),
                        ],
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "price_at",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="قیمت هنگام ثبت"
                    ),
                ),
                (
                    "source",
                    models.CharField(default="web", max_length=10, verbose_name="از"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="ثبت",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="خبر داده شد"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="فرش",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست «خبرم کن»",
                "verbose_name_plural": "درخواست\u200cهای «خبرم کن»",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("sent_at__isnull", True)),
                        fields=("product", "mobile", "kind"),
                        name="alert_once_open",
                    )
                ],
            },
        ),
    ]
