# Generated by Django 5.2.17 on 2026-10-04 10:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_percent",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="درصد بیعانه"
                    ),
                ),
                (
                    "free_shipping_min",
                    models.PositiveBigIntegerField(
                        default=50000000,
                        help_text="فقط برای سفارش\u200cهایی که کل مبلغ را آنلاین پرداخت می\u200cکنند",
                        verbose_name="حداقل مبلغ ارسال رایگان (تومان)",
                    ),
                ),
                (
                    "allow_full",
                    models.BooleanField(
                        default=True, verbose_name="پرداخت کامل آنلاین فعال باشد"
                    ),
                ),
                (
                    "allow_deposit",
                    models.BooleanField(
                        default=True, verbose_name="پرداخت بیعانه فعال باشد"
                    ),
                ),
                (
                    "sep_enabled",
                    models.BooleanField(
                        default=True, verbose_name="درگاه سامان (سپ) فعال باشد"
                    ),
                ),
                (
                    "zarinpal_enabled",
                    models.BooleanField(
                        default=True, verbose_name="درگاه زرین\u200cپال فعال باشد"
                    ),
                ),
                (
                    "checkout_note",
                    models.TextField(blank=True, verbose_name="توضیح صفحهٔ تسویه حساب"),
                ),
                (
                    "admin_mobiles",
                    models.CharField(
                        blank=True,
                        help_text="با ویرگول جدا کنید",
                        max_length=200,
                        verbose_name="موبایل مدیران برای اطلاع از سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات فروش",
                "verbose_name_plural": "تنظیمات فروش",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="شمارهٔ سفارش"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("deposit_paid", "بیعانه پرداخت شد"),
                            ("paid", "پرداخت کامل"),
                            ("processing", "در حال آماده\u200cسازی"),
                            ("shipped", "ارسال شد"),
                            ("completed", "تحویل شد"),
                            ("cancelled", "لغو شده"),
                            ("refunded", "مسترد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="نام خانوادگی"),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("province", models.CharField(max_length=60, verbose_name="استان")),
                ("city", models.CharField(max_length=80, verbose_name="شهر")),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="کد پستی"),
                ),
                ("note", models.TextField(blank=True, verbose_name="توضیح مشتری")),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("full", "پرداخت کامل آنلاین"),
                            ("deposit", "بیعانه آنلاین، بقیه موقع تحویل"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "shipping_mode",
                    models.CharField(
                        choices=[
                            ("free", "ارسال رایگان"),
                            ("cod", "پس\u200cکرایه (هزینهٔ ارسال با مشتری)"),
                        ],
                        default="cod",
                        max_length=10,
                        verbose_name="ارسال",
                    ),
                ),
                (
                    "items_total",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="جمع کالاها (تومان)"
                    ),
                ),
                (
                    "deposit_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="درصد بیعانه"
                    ),
                ),
                (
                    "online_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="مبلغ پرداخت آنلاین"
                    ),
                ),
                (
                    "paid_amount",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="پرداخت\u200cشده"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد رهگیری ارسال"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ ثبت",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="کالا")),
                (
                    "size_label",
                    models.CharField(blank=True, max_length=150, verbose_name="سایز"),
                ),
                (
                    "unit_price",
                    models.PositiveBigIntegerField(verbose_name="قیمت واحد"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.variation",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم سفارش",
                "verbose_name_plural": "اقلام سفارش",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(max_length=20, verbose_name="درگاه")),
                ("amount", models.PositiveBigIntegerField(verbose_name="مبلغ (تومان)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("init", "ارسال به درگاه"),
                            ("ok", "موفق"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="init",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        verbose_name="توکن/Authority",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد پیگیری بانک"
                    ),
                ),
                (
                    "card",
                    models.CharField(blank=True, max_length=40, verbose_name="کارت"),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=300, verbose_name="پیام"),
                ),
                (
                    "raw",
                    models.JSONField(blank=True, default=dict, verbose_name="پاسخ خام"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
