# Generated by Django 5.2.17 on 2026-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="sep_terminal_id",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="شمارهٔ ترمینال سامان"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="smsir_admin_template_id",
            field=models.CharField(
                blank=True,
                help_text="متغیرها: ORDER، NAME و AMOUNT",
                max_length=20,
                verbose_name="شمارهٔ قالب پیامک سفارش به مدیر",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="smsir_api_key",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="کلید API پنل sms.ir"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="smsir_order_template_id",
            field=models.CharField(
                blank=True,
                help_text="متغیرها: ORDER و AMOUNT",
                max_length=20,
                verbose_name="شمارهٔ قالب پیامک پرداخت به مشتری",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="smsir_otp_template_id",
            field=models.CharField(
                blank=True,
                help_text="قالب با متغیر CODE",
                max_length=20,
                verbose_name="شمارهٔ قالب کد ورود",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="zarinpal_merchant_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="مرچنت\u200cکد زرین\u200cپال"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="zarinpal_sandbox",
            field=models.BooleanField(
                default=False, verbose_name="زرین\u200cپال در حالت آزمایشی (sandbox)"
            ),
        ),
    ]
