# Generated by Django 5.2.17 on 2026-10-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_integration_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="wp_payment",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=200,
                verbose_name="روش پرداخت در وردپرس",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wp_status",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=40,
                verbose_name="وضعیت در وردپرس",
            ),
        ),
    ]
