# Generated by Django 5.2.17 on 2026-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_wp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="smsir_line_number",
            field=models.CharField(
                blank=True,
                help_text="خط اختصاصی یا خدماتی در پنل sms.ir (برای پیامک گروهی)",
                max_length=20,
                verbose_name="شمارهٔ خط ارسال پیامک گروهی",
            ),
        ),
    ]
