# Generated by Django 5.2.17 on 2026-10-04 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installments", "0001_initial"),
        ("shop", "0004_sms_campaigns"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="installment",
            field=models.JSONField(blank=True, default=dict, verbose_name="جدول اقساط"),
        ),
        migrations.AddField(
            model_name="order",
            name="installment_info",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="مشخصات متقاضی اقساط"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="installment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="installments.installmentplan",
                verbose_name="روش اقساط",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="installment_reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ بررسی اقساط"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="installment_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("review", "در انتظار بررسی مدارک"),
                    ("approved", "تأیید شد"),
                    ("rejected", "رد شد"),
                    ("done", "تکمیل شد (چک\u200cها / بتا ثبت شد)"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="وضعیت اقساط",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("full", "پرداخت کامل آنلاین"),
                    ("deposit", "بیعانه آنلاین، بقیه موقع تحویل"),
                    ("installment", "خرید اقساطی"),
                ],
                default="full",
                max_length=20,
                verbose_name="نوع پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("on_hold", "در انتظار بررسی اقساط"),
                    ("deposit_paid", "بیعانه پرداخت شد"),
                    ("paid", "پرداخت کامل"),
                    ("processing", "در حال آماده\u200cسازی"),
                    ("shipped", "ارسال شد"),
                    ("completed", "تحویل شد"),
                    ("cancelled", "لغو شده"),
                    ("refunded", "مسترد شده"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
