# Generated by Django 5.2.17 on 2026-10-05 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_installments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, verbose_name="کد تخفیف"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="از جمع کالاها کم شده است",
                verbose_name="تخفیف (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="آخرین یادآوری پرداخت",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reminded_count",
            field=models.PositiveSmallIntegerField(
                default=0, editable=False, verbose_name="تعداد یادآوری پرداخت"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="review_invited_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="دعوت به ثبت نظر"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="referral_enabled",
            field=models.BooleanField(
                default=False,
                help_text="هر مشتری یک کد اختصاصی می\u200cگیرد؛ دوستش با آن تخفیف می\u200cگیرد و خودش بعد از خرید دوست، کد هدیه.",
                verbose_name="کد معرفی دوستان فعال باشد",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="referral_max",
            field=models.PositiveBigIntegerField(
                default=2000000, verbose_name="سقف تخفیف دوست (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="referral_min_order",
            field=models.PositiveBigIntegerField(
                default=10000000, verbose_name="حداقل خرید برای کد معرفی (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="referral_percent",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="تخفیف دوستِ معرفی\u200cشده (درصد)"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="referral_reward",
            field=models.PositiveBigIntegerField(
                default=1000000,
                help_text="بعد از خرید دوست، یک کد تخفیف با این مبلغ برای معرف ساخته و پیامک می\u200cشود",
                verbose_name="هدیهٔ معرف (تومان)",
            ),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="حروف انگلیسی و عدد؛ بزرگ و کوچک فرقی ندارد",
                        max_length=40,
                        unique=True,
                        verbose_name="کد",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="مثل «تخفیف اولین خرید»",
                        max_length=120,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت (تومان)")],
                        default="percent",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "value",
                    models.PositiveBigIntegerField(
                        help_text="برای درصدی: درصد؛ برای ثابت: تومان",
                        verbose_name="مقدار",
                    ),
                ),
                (
                    "max_discount",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="۰ یعنی بدون سقف",
                        verbose_name="سقف تخفیف (تومان)",
                    ),
                ),
                (
                    "min_order",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="حداقل مبلغ سبد (تومان)"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="شروع"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پایان"),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="۰ یعنی بی\u200cسقف",
                        verbose_name="سقف کل استفاده",
                    ),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="۰ یعنی بی\u200cسقف",
                        verbose_name="سقف استفادهٔ هر مشتری",
                    ),
                ),
                (
                    "first_order_only",
                    models.BooleanField(default=False, verbose_name="فقط اولین خرید"),
                ),
                (
                    "app_only",
                    models.BooleanField(default=False, verbose_name="فقط خرید از اپ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ساخته شده"
                    ),
                ),
                (
                    "for_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="فقط برای این مشتری",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر پر باشد، کد معرفی همین مشتری است و بعد از خرید دوستش هدیه می\u200cگیرد",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="صاحب کد معرفی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
                "ordering": ["-created_at"],
            },
        ),
    ]
