# Generated by Django 5.2.17 on 2026-10-07 21:37

import django.db.models.deletion
import django.utils.timezone
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_size_choice"),
        ("pricing", "0004_price_list"),
        ("shop", "0006_coupons_reminders"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="روی قیمت روز همان سایز",
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "fixed_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="اگر پر شود به\u200cجای درصد تخفیف همین قیمت گرفته می\u200cشود.",
                        null=True,
                        verbose_name="یا قیمت ثابت (تومان)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="تعداد موجود در انبار"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="شروع"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        default=shop.models._in_24h,
                        help_text="شمارندهٔ معکوس تا همین زمان؛ بعدش قیمت ویژه تمام می\u200cشود.",
                        verbose_name="پایان",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="به مشتری نشان داده نمی\u200cشود؛ مثلاً محل فرش در انبار",
                        max_length=200,
                        verbose_name="یادداشت داخلی",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_offers",
                        to="catalog.product",
                        verbose_name="فرش",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="pricing.size",
                        verbose_name="سایز",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرصت ویژهٔ خرید",
                "verbose_name_plural": "فرصت\u200cهای ویژهٔ خرید",
                "ordering": ["ends_at"],
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="shop.specialoffer",
                verbose_name="فرصت ویژه",
            ),
        ),
    ]
