# Generated by Django 5.2.17 on 2026-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_special_offers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialoffer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "فرصت ویژهٔ خرید",
                "verbose_name_plural": "فرصت\u200cهای ویژهٔ خرید",
            },
        ),
        migrations.AlterField(
            model_name="specialoffer",
            name="ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="خالی = تا وقتی تخته\u200cها فروخته شوند یا «تعداد» را صفر کنید. اگر پر شود، شمارندهٔ معکوس تا همین زمان نشان داده می\u200cشود و بعدش قیمت ویژه تمام می\u200cشود.",
                null=True,
                verbose_name="پایان (اختیاری)",
            ),
        ),
    ]
