# Generated by Django 5.2.17 on 2026-10-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        ("shop", "0008_offer_no_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="commission_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="کمیسیون (درصد)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="market.sellerorder",
                verbose_name="سفارش فروشنده",
            ),
        ),
    ]
