# Generated by Django 5.2.17 on 2026-10-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_orderitem_commission_percent_orderitem_seller_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="for_mobile",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="کد شخصی کمپین\u200cها؛ فقط مشتری با همین شماره می\u200cتواند استفاده کند",
                max_length=11,
                verbose_name="فقط برای این موبایل",
            ),
        ),
    ]
