# Generated by Django 5.2.17 on 2026-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_coupon_for_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="busy_enabled",
            field=models.BooleanField(default=True, verbose_name="اطلاعیهٔ فصل شلوغ"),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="busy_from",
            field=models.CharField(
                default="10-01",
                help_text="مثل 10-01 یعنی اول دی",
                max_length=5,
                verbose_name="شروع فصل شلوغ (ماه-روز شمسی)",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="busy_message",
            field=models.CharField(
                default="در دی و بهمن به\u200cخاطر حجم بالای سفارش\u200cهای عید، بافت و ارسال فرش ممکن است چند روز بیشتر از معمول طول بکشد.",
                max_length=300,
                verbose_name="پیام فصل شلوغ",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="busy_to",
            field=models.CharField(
                default="11-30", max_length=5, verbose_name="پایان فصل شلوغ"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pause_enabled",
            field=models.BooleanField(
                default=True,
                help_text="در این بازه فرش\u200cهایی که باید بافته شوند سفارش گرفته نمی\u200cشوند؛ فرصت\u200cهای ویژه (آماده در انبار) فروخته می\u200cشوند.",
                verbose_name="توقف سفارش بافت در پایان سال",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pause_from",
            field=models.CharField(
                default="12-01",
                help_text="مثل 12-01 یعنی اول اسفند",
                max_length=5,
                verbose_name="شروع توقف (ماه-روز شمسی)",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pause_message",
            field=models.CharField(
                default="سفارش فرش\u200cهایی که باید بافته شوند تا ۱۵ فروردین پذیرفته نمی\u200cشود؛ فرش\u200cهای «فرصت ویژه» آماده\u200cاند و فوری ارسال می\u200cشوند.",
                max_length=300,
                verbose_name="پیام توقف سفارش",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pause_to",
            field=models.CharField(
                default="01-15",
                help_text="مثل 01-15 یعنی ۱۵ فروردین",
                max_length=5,
                verbose_name="پایان توقف",
            ),
        ),
    ]
