# Generated by Django 5.2.17 on 2026-10-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0004_price_list"),
        ("shop", "0011_shopsettings_busy_enabled_shopsettings_busy_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialoffer",
            name="base_album",
            field=models.ForeignKey(
                blank=True,
                help_text="برای فرشی که قیمت ندارد (مثلاً از تولید خارج شده): قیمت روز این سایز از همین آلبوم حساب می\u200cشود. خود فرش و سایزهای دیگرش دست نمی\u200cخورد.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pricing.album",
                verbose_name="قیمت از آلبوم",
            ),
        ),
        migrations.AddField(
            model_name="specialoffer",
            name="base_price",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="قیمت واقعی همین سایز پیش از تخفیف؛ تخفیف روی همین عدد زده می\u200cشود و خط\u200cخورده نمایش داده می\u200cشود. عدد بالاتر از قیمت واقعی، تخفیف صوری و خلاف قانون است.",
                null=True,
                verbose_name="یا قیمت پایهٔ دستی (تومان)",
            ),
        ),
    ]
