# Generated by Django 5.2.17 on 2026-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_offer_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sms_campaign_id",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, null=True, verbose_name="کمپین پیامکی"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="src",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, verbose_name="منبع ورود"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="src_name",
            field=models.CharField(blank=True, max_length=60, verbose_name="نام منبع"),
        ),
        migrations.AddField(
            model_name="order",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=80, verbose_name="کمپین UTM"),
        ),
    ]
