# Generated by Django 5.2.17 on 2026-10-05 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_filter_attrs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(blank=True, max_length=15, verbose_name="موبایل"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="نام"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "عکس فرش"), ("text", "توضیح نیاز")],
                        default="photo",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="توضیح مشتری")),
                (
                    "wanted",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="نیازها، سایز و بودجه\u200cای که مشتری انتخاب کرده",
                        verbose_name="خواسته\u200cها",
                    ),
                ),
                (
                    "photo",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        verbose_name="مسیر عکس (خصوصی)",
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        editable=False,
                        verbose_name="رنگ\u200cهای غالب عکس",
                    ),
                ),
                (
                    "auto_products",
                    models.JSONField(
                        blank=True,
                        default=list,
                        editable=False,
                        verbose_name="پیشنهاد خودکار",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "تازه"),
                            ("answered", "پاسخ داده شد"),
                            ("closed", "بسته"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True,
                        help_text="این متن در اپ برای مشتری نمایش داده می\u200cشود.",
                        verbose_name="پاسخ کارشناس",
                    ),
                ),
                (
                    "notify_sms",
                    models.BooleanField(
                        default=True,
                        help_text="بعد از پاسخ، یک پیامک کوتاه برای مشتری فرستاده می\u200cشود (اگر خط پیامک تنظیم شده باشد).",
                        verbose_name="خبر دادن با پیامک",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="زمان ثبت",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پاسخ"
                    ),
                ),
                (
                    "seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="دیده\u200cشده توسط مشتری"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="فرش\u200cهای پیشنهادی کارشناس",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finder_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست فرش\u200cیاب",
                "verbose_name_plural": "درخواست\u200cهای فرش\u200cیاب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="همان چیزی که مشتری می\u200cبیند؛ مثل «ضخیم و کلفت»",
                        max_length=80,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="مثل «پرز بلند، نرم زیر پا»",
                        max_length=140,
                        verbose_name="توضیح کوتاه",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("feel", "جنس و ضخامت"),
                            ("color", "رنگ"),
                            ("style", "سبک و طرح"),
                            ("use", "کاربرد و فضا"),
                        ],
                        default="style",
                        max_length=10,
                        verbose_name="گروه",
                    ),
                ),
                (
                    "swatch",
                    models.CharField(
                        blank=True,
                        help_text="برای نیازهای رنگی؛ مثل #B3202A",
                        max_length=7,
                        verbose_name="رنگ نمونه",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="نام نماد در اپ (اختیاری)",
                        max_length=30,
                        verbose_name="نماد",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="با ویرگول جدا کنید. وقتی مشتری در جستجو یکی از این\u200cها را بنویسد، همین نیاز فهمیده می\u200cشود. مثل «ضخیم، کلفت، پرزدار، نرم»",
                        verbose_name="کلمه\u200cهایی که مشتری می\u200cگوید",
                    ),
                ),
                (
                    "term_keywords",
                    models.CharField(
                        blank=True,
                        help_text="هر مقدار ویژگی بالا که یکی از این کلمه\u200cها در نامش باشد؛ مثل «قرمز، لاکی، زرشکی». مقدارهای تازه خودکار حساب می\u200cشوند.",
                        max_length=400,
                        verbose_name="مقدارهایی که این کلمه\u200cها را دارند",
                    ),
                ),
                (
                    "title_keywords",
                    models.CharField(
                        blank=True,
                        help_text="فرش\u200cهایی که یکی از این کلمه\u200cها در عنوانشان است؛ مثل «لچک، ترنج، افشان»",
                        max_length=400,
                        verbose_name="کلمه در عنوان فرش",
                    ),
                ),
                (
                    "exclude_keywords",
                    models.CharField(
                        blank=True,
                        help_text="مثل «برجسته»",
                        max_length=400,
                        verbose_name="به\u200cجز فرش\u200cهایی که این کلمه\u200cها در عنوانشان است",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="catalog.category",
                        verbose_name="دسته\u200cها (با زیردسته\u200cها)",
                    ),
                ),
                (
                    "exclude_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="catalog.category",
                        verbose_name="به\u200cجز این دسته\u200cها",
                    ),
                ),
                (
                    "term_attribute",
                    models.ForeignKey(
                        blank=True,
                        help_text="مثلاً «رنگ زمینه»",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.attribute",
                        verbose_name="ویژگی برای کلمه\u200cهای مقدار",
                    ),
                ),
                (
                    "terms",
                    models.ManyToManyField(
                        blank=True,
                        help_text="مثل شانه ۷۰۰، شانه ۱۰۰۰",
                        related_name="+",
                        to="catalog.attributeterm",
                        verbose_name="مقدار ویژگی\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "نیاز مشتری",
                "verbose_name_plural": "نیازهای مشتری (فرش\u200cیاب)",
                "ordering": ["group", "order", "pk"],
            },
        ),
    ]
