# Generated by Django 5.2.17 on 2026-10-09 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0010_coupon_for_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("buyers", "همهٔ خریداران"),
                            ("inactive", "خریدارانی که مدتی نخریده\u200cاند"),
                            ("vip", "مشتریان وفادار"),
                            ("active", "فعال (خرید در ۶ ماه اخیر)"),
                            ("new", "خریداران تازه (۶۰ روز اخیر)"),
                            ("at_risk", "در خطر ریزش (۶ تا ۱۲ ماه بی\u200cخرید)"),
                            ("lost", "از دست رفته (بیش از یک سال)"),
                            ("unpaid", "سفارش داده ولی هرگز پرداخت نکرده"),
                            ("registered", "ثبت\u200cنام\u200cکرده بدون سفارش"),
                            ("custom", "شماره\u200cهای دلخواه"),
                        ],
                        default="buyers",
                        max_length=12,
                        verbose_name="گیرنده\u200cها",
                    ),
                ),
                (
                    "inactive_days",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="فقط برای «مدتی نخریده\u200cاند»",
                        verbose_name="بی\u200cخریدی دست\u200cکم (روز)",
                    ),
                ),
                (
                    "custom_numbers",
                    models.TextField(
                        blank=True,
                        help_text="هر شماره در یک خط",
                        verbose_name="شماره\u200cهای دلخواه",
                    ),
                ),
                (
                    "discount",
                    models.PositiveBigIntegerField(
                        default=2000000,
                        help_text="۰ یعنی پیامک بدون کد تخفیف",
                        verbose_name="مبلغ تخفیف (تومان)",
                    ),
                ),
                (
                    "min_order",
                    models.PositiveBigIntegerField(
                        default=40000000, verbose_name="حداقل خرید (تومان)"
                    ),
                ),
                (
                    "valid_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="مهلت استفاده (روز)"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        default="{name} عزیز، به پاس خرید قبلی\u200cتان از ایران کارپت، کد تخفیف {discount} تومانی برای شما:\n{code}\nبرای خرید بالای {min} تومان، تا {until}. {site}",
                        help_text="{name} نام، {code} کد تخفیف شخصی، {discount} مبلغ تخفیف، {min} حداقل خرید، {until} تاریخ پایان، {site} نشانی سایت",
                        verbose_name="متن پیامک",
                    ),
                ),
                (
                    "code_prefix",
                    models.CharField(blank=True, editable=False, max_length=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("sending", "در حال ارسال"),
                            ("done", "ارسال شد"),
                            ("stopped", "متوقف شد"),
                            ("failed", "ناموفق"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(default=0, verbose_name="گیرنده"),
                ),
                (
                    "sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ارسال\u200cشده"
                    ),
                ),
                (
                    "failed",
                    models.PositiveIntegerField(default=0, verbose_name="ناموفق"),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="آخرین خطا"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ساخته شده"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع ارسال"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان ارسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "کمپین",
                "verbose_name_plural": "کمپین\u200cهای پیامکی و کد تخفیف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_sms",
                    models.BooleanField(
                        default=True, verbose_name="پیامک ثبت سفارش به مشتری"
                    ),
                ),
                (
                    "order_text",
                    models.TextField(
                        default="{name} عزیز، سفارش {number} در ایران کارپت ثبت شد. مبلغ: {total} تومان.\nاگر پرداخت ناتمام ماند، از این پیوند کامل کنید: {pay_link}\nپیگیری: {link}",
                        verbose_name="متن ثبت سفارش",
                    ),
                ),
                (
                    "order_installment_text",
                    models.TextField(
                        default="{name} عزیز، درخواست خرید اقساطی سفارش {number} ثبت شد. پس از بررسی مدارک، نتیجه را پیامک می\u200cکنیم.\nپیگیری: {link}",
                        verbose_name="متن ثبت سفارش اقساطی",
                    ),
                ),
                (
                    "admin_sms",
                    models.BooleanField(
                        default=True,
                        help_text="به شماره\u200cهای «تنظیمات ← فروش و ارسال ← موبایل مدیران»",
                        verbose_name="پیامک سفارش تازه به مدیران",
                    ),
                ),
                (
                    "admin_text",
                    models.TextField(
                        default="سفارش تازه {number}\n{name} | {mobile} | {city}\nمبلغ: {total} تومان | {mode}\n{panel}",
                        verbose_name="متن سفارش تازه (مدیر)",
                    ),
                ),
                (
                    "paid_text",
                    models.TextField(
                        default="{name} عزیز، پرداخت {paid} تومانی سفارش {number} انجام شد و سفارش شما در صف آماده\u200cسازی است.\nپیگیری: {link}",
                        help_text="اگر در «پیامک» شمارهٔ قالب تأیید سفارش sms.ir وارد شده باشد، همان قالب فرستاده می\u200cشود.",
                        verbose_name="متن پرداخت موفق (مشتری)",
                    ),
                ),
                (
                    "admin_paid_text",
                    models.TextField(
                        default="پرداخت شد: سفارش {number} | {paid} تومان | {name}\n{panel}",
                        verbose_name="متن پرداخت موفق (مدیر)",
                    ),
                ),
                (
                    "status_sms",
                    models.BooleanField(
                        default=True,
                        help_text="ارسال، تحویل و لغو؛ وقتی وضعیت را در پنل عوض می\u200cکنید",
                        verbose_name="پیامک تغییر وضعیت سفارش",
                    ),
                ),
                (
                    "shipped_text",
                    models.TextField(
                        default="{name} عزیز، سفارش {number} از کاشان ارسال شد.{tracking}\nپیگیری: {link}",
                        verbose_name="متن ارسال شد",
                    ),
                ),
                (
                    "completed_text",
                    models.TextField(
                        default="{name} عزیز، سفارش {number} تحویل شد. امیدواریم از فرش\u200cتان لذت ببرید. پرسشی داشتید با {phone} در تماس باشید.",
                        verbose_name="متن تحویل شد",
                    ),
                ),
                (
                    "cancelled_text",
                    models.TextField(
                        default="{name} عزیز، سفارش {number} لغو شد. اگر پرسشی دارید با {phone} در تماس باشید.",
                        verbose_name="متن لغو شد",
                    ),
                ),
                (
                    "remind_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="پیگیری سفارش\u200cهای پرداخت\u200cنشده",
                    ),
                ),
                (
                    "remind_hours",
                    models.CharField(
                        default="1,24,72",
                        help_text="با ویرگول؛ برای هر عدد یک پیامک. متن اول، دوم و سوم به ترتیب.",
                        max_length=40,
                        verbose_name="زمان یادآوری\u200cها (ساعت بعد از ثبت)",
                    ),
                ),
                (
                    "remind_text_1",
                    models.TextField(
                        default="{name} عزیز، سفارش {number} شما در ایران کارپت ثبت شده ولی هنوز پرداخت نشده. فرش\u200cهای انتخابی\u200cتان را برایتان نگه داشته\u200cایم. پرداخت: {pay_link}",
                        verbose_name="یادآوری اول",
                    ),
                ),
                (
                    "remind_text_2",
                    models.TextField(
                        default="{name} عزیز، به\u200cدلیل نوسان قیمت مواد اولیه، قیمت فرش\u200cها ممکن است به\u200cزودی تغییر کند. سفارش {number} هنوز با قیمت ثبت\u200cشده برایتان نگه داشته شده؛ برای تکمیل، پرداخت را انجام دهید. پرداخت: {pay_link}",
                        verbose_name="یادآوری دوم (نوسان قیمت)",
                    ),
                ),
                (
                    "remind_text_3",
                    models.TextField(
                        default="{name} عزیز، امروز آخرین فرصت پرداخت سفارش {number} با قیمت ثبت\u200cشده است. پرداخت: {pay_link}",
                        verbose_name="یادآوری سوم (آخرین مهلت)",
                    ),
                ),
                (
                    "winback_auto",
                    models.BooleanField(
                        default=False,
                        verbose_name="کد تخفیف خودکار برای مشتریانی که مدتی نخریده\u200cاند",
                    ),
                ),
                (
                    "winback_days",
                    models.PositiveIntegerField(
                        default=180, verbose_name="بعد از چند روز بی\u200cخریدی"
                    ),
                ),
                (
                    "winback_amount",
                    models.PositiveBigIntegerField(
                        default=2000000, verbose_name="مبلغ تخفیف (تومان)"
                    ),
                ),
                (
                    "winback_min_order",
                    models.PositiveBigIntegerField(
                        default=40000000, verbose_name="حداقل خرید (تومان)"
                    ),
                ),
                (
                    "winback_valid_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="مهلت استفاده (روز)"
                    ),
                ),
                (
                    "winback_text",
                    models.TextField(
                        default="{name} عزیز، دلمان برایتان تنگ شده! کد تخفیف {discount} تومانی ویژهٔ شما:\n{code}\nبرای خرید بالای {min} تومان، تا {until}. {site}",
                        verbose_name="متن پیامک بازگشت",
                    ),
                ),
                (
                    "vip_total",
                    models.PositiveBigIntegerField(
                        default=150000000,
                        verbose_name="مشتری وفادار از جمع خرید (تومان)",
                    ),
                ),
                (
                    "vip_orders",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="یا از تعداد سفارش پرداخت\u200cشده"
                    ),
                ),
                (
                    "marketing_footer",
                    models.CharField(
                        blank=True,
                        default="لغو۱۱",
                        help_text="برای پیامک\u200cهای تبلیغاتی (کمپین و بازگشت)؛ پیامک\u200cهای سفارش این را ندارند.",
                        max_length=40,
                        verbose_name="پایان پیامک\u200cهای تبلیغاتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات باشگاه مشتریان",
            },
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("order", "ثبت سفارش"),
                            ("admin", "خبر به مدیر"),
                            ("paid", "پرداخت موفق"),
                            ("status", "تغییر وضعیت"),
                            ("remind", "یادآوری پرداخت"),
                            ("campaign", "کمپین"),
                            ("winback", "بازگشت مشتری"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن")),
                ("ok", models.BooleanField(default=False, verbose_name="رسید")),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="زمان",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="crm.campaign",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_logs",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیامک فرستاده\u200cشده",
                "verbose_name_plural": "پیامک\u200cهای فرستاده\u200cشده",
                "ordering": ["-created_at"],
            },
        ),
    ]
