# Generated by Django 5.2.17 on 2026-10-09 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_product_seller_variation_stock_qty"),
        ("crm", "0001_initial"),
        ("pricing", "0004_price_list"),
        ("shop", "0010_coupon_for_mobile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("target", models.CharField(db_index=True, max_length=500)),
                ("hits", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "پیوند کوتاه",
                "verbose_name_plural": "پیوندهای کوتاه",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="album",
            field=models.ForeignKey(
                blank=True,
                help_text="فقط برای «علاقه\u200cمندان یک آلبوم»",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="pricing.album",
                verbose_name="آلبوم",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="event_date",
            field=models.CharField(
                blank=True,
                help_text="برای متغیر {date}؛ مثل «شنبه ۲۶ مهر»",
                max_length=60,
                verbose_name="زمان افزایش قیمت",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="album_text",
            field=models.TextField(
                default="{name} عزیز، قیمت فرش\u200cهای «{album}» از {date} افزایش پیدا می\u200cکند. اگر فرشی از این مجموعه در نظر دارید، تا پیش از آن با قیمت فعلی سفارش دهید: {site}",
                help_text="متغیرها: {album} نام آلبوم و {date} زمان افزایش. از «آلبوم\u200cهای قیمت ← عملیات گروهی» ساخته می\u200cشود.",
                verbose_name="متن پیش\u200cفرض اطلاع افزایش قیمت آلبوم",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="birthday_amount",
            field=models.PositiveBigIntegerField(
                default=1000000, verbose_name="مبلغ هدیهٔ تولد (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="birthday_enabled",
            field=models.BooleanField(
                default=True,
                help_text="مشتری تاریخ تولدش را در صفحهٔ باشگاه ثبت می\u200cکند",
                verbose_name="هدیهٔ تولد",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="birthday_min_order",
            field=models.PositiveBigIntegerField(
                default=20000000, verbose_name="حداقل خرید برای کد تولد (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="birthday_text",
            field=models.TextField(
                default="{name} عزیز، تولدتان مبارک! ایران کارپت یک کد هدیهٔ {discount} تومانی برایتان کنار گذاشته:\n{code}\nبرای خرید بالای {min} تومان، تا {until}. {site}",
                verbose_name="متن پیامک تولد",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="birthday_valid_days",
            field=models.PositiveIntegerField(
                default=14, verbose_name="مهلت کد تولد (روز)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="cart_enabled",
            field=models.BooleanField(
                default=True,
                help_text="برای مشتری واردشده\u200cای که فرش در سبد گذاشته و سفارش نداده؛ یک\u200cبار",
                verbose_name="یادآوری سبد خرید رهاشده",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="cart_hours",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="چند ساعت بعد از آخرین تغییر سبد"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="cart_text",
            field=models.TextField(
                default="{name} عزیز، فرش\u200cهایی که در سبد خریدتان گذاشتید هنوز منتظر شماست. برای تکمیل خرید: {cart_link}",
                verbose_name="متن یادآوری سبد",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="point_value",
            field=models.PositiveIntegerField(
                default=10000,
                help_text="۱۰ هزار تومان برای هر میلیون یعنی ۱٪ برگشت",
                verbose_name="ارزش هر امتیاز (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="points_enabled",
            field=models.BooleanField(
                default=True,
                help_text="امتیاز از خریدهای پرداخت\u200cشده؛ مشتری در «حساب کاربری ← باشگاه» آن را به کد تخفیف تبدیل می\u200cکند",
                verbose_name="امتیاز خرید",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="points_min_order",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="حداقل خرید برای کد امتیاز (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="points_min_redeem",
            field=models.PositiveIntegerField(
                default=100, verbose_name="کمترین امتیاز برای تبدیل"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="points_per",
            field=models.PositiveBigIntegerField(
                default=1000000, verbose_name="هر چند تومان خرید = یک امتیاز"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="points_since",
            field=models.DateField(
                blank=True,
                help_text="خالی یعنی خریدهای قبلی (دورهٔ وردپرس هم) امتیاز دارند",
                null=True,
                verbose_name="امتیاز خریدهای از این تاریخ به بعد",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="points_valid_days",
            field=models.PositiveIntegerField(
                default=60, verbose_name="مهلت کد امتیاز (روز)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="review_reward_amount",
            field=models.PositiveBigIntegerField(
                default=500000, verbose_name="مبلغ جایزهٔ نظر (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="review_reward_enabled",
            field=models.BooleanField(
                default=True,
                help_text="بعد از تأیید نظرِ خریدار که عکس دارد، کد هدیه پیامک می\u200cشود (هر شماره هر ۶۰ روز یک\u200cبار)",
                verbose_name="جایزهٔ نظر با عکس",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="review_reward_min_order",
            field=models.PositiveBigIntegerField(
                default=10000000, verbose_name="حداقل خرید برای کد نظر (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="review_reward_text",
            field=models.TextField(
                default="{name} عزیز، ممنون از نظر و عکسی که فرستادید. کد هدیهٔ {discount} تومانی شما:\n{code}\nبرای خرید بالای {min} تومان، تا {until}.",
                verbose_name="متن پیامک جایزهٔ نظر",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="review_reward_valid_days",
            field=models.PositiveIntegerField(
                default=60, verbose_name="مهلت کد نظر (روز)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="short_links",
            field=models.BooleanField(
                default=True,
                help_text="دامنهٔ کوتاه همان «تنظیمات ← همکاری در فروش» است؛ اگر خالی باشد پیوند با دامنهٔ اصلی ساخته می\u200cشود",
                verbose_name="پیوند کوتاه در پیامک\u200cها (crpt.ir)",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="segment",
            field=models.CharField(
                choices=[
                    ("buyers", "همهٔ خریداران"),
                    ("inactive", "خریدارانی که مدتی نخریده\u200cاند"),
                    ("vip", "مشتریان وفادار"),
                    ("active", "فعال (خرید در ۶ ماه اخیر)"),
                    ("new", "خریداران تازه (۶۰ روز اخیر)"),
                    ("at_risk", "در خطر ریزش (۶ تا ۱۲ ماه بی\u200cخرید)"),
                    ("lost", "از دست رفته (بیش از یک سال)"),
                    (
                        "album",
                        "علاقه\u200cمندان یک آلبوم (دیده، در سبد یا سفارش ناتمام)",
                    ),
                    ("unpaid", "سفارش داده ولی هرگز پرداخت نکرده"),
                    ("registered", "ثبت\u200cنام\u200cکرده بدون سفارش"),
                    ("custom", "شماره\u200cهای دلخواه"),
                ],
                default="buyers",
                max_length=12,
                verbose_name="گیرنده\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="crmsettings",
            name="order_text",
            field=models.TextField(
                default="{name} عزیز، سفارش {number} در ایران کارپت ثبت شد. {due_line}.\nاگر پرداخت ناتمام ماند: {pay_link}",
                verbose_name="متن ثبت سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="crmsettings",
            name="paid_text",
            field=models.TextField(
                default="{name} عزیز، پرداخت {paid} تومانی سفارش {number} انجام شد و سفارش شما در صف آماده\u200cسازی است.{points_line}\nپیگیری: {link}",
                help_text="اگر در «پیامک» شمارهٔ قالب تأیید سفارش sms.ir وارد شده باشد، همان قالب فرستاده می\u200cشود.",
                verbose_name="متن پرداخت موفق (مشتری)",
            ),
        ),
        migrations.AlterField(
            model_name="crmsettings",
            name="remind_text_1",
            field=models.TextField(
                default="{name} عزیز، سفارش {number} شما هنوز پرداخت نشده و فرش\u200cهایتان را برایتان نگه داشته\u200cایم. {due_line}. پرداخت: {pay_link}",
                verbose_name="یادآوری اول",
            ),
        ),
        migrations.AlterField(
            model_name="crmsettings",
            name="remind_text_2",
            field=models.TextField(
                default="{name} عزیز، به\u200cدلیل نوسان قیمت\u200cها، قیمت فرش\u200cها ممکن است به\u200cزودی تغییر کند. سفارش {number} هنوز با قیمت ثبت\u200cشده برایتان نگه داشته شده؛ برای تکمیل سفارش، {due} را پرداخت کنید. پرداخت: {pay_link}",
                verbose_name="یادآوری دوم (نوسان قیمت)",
            ),
        ),
        migrations.AlterField(
            model_name="crmsettings",
            name="remind_text_3",
            field=models.TextField(
                default="{name} عزیز، امروز آخرین فرصت پرداخت سفارش {number} با قیمت ثبت\u200cشده است. {due_line}. پرداخت: {pay_link}",
                verbose_name="یادآوری سوم (آخرین مهلت)",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order", "ثبت سفارش"),
                    ("admin", "خبر به مدیر"),
                    ("paid", "پرداخت موفق"),
                    ("status", "تغییر وضعیت"),
                    ("remind", "یادآوری پرداخت"),
                    ("campaign", "کمپین"),
                    ("winback", "بازگشت مشتری"),
                    ("birthday", "تولد"),
                    ("cart", "سبد رهاشده"),
                    ("review", "جایزهٔ نظر"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="نوع",
            ),
        ),
        migrations.CreateModel(
            name="CartSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_snapshot",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد ذخیره\u200cشده",
                "verbose_name_plural": "سبدهای ذخیره\u200cشده",
            },
        ),
        migrations.CreateModel(
            name="PointRedeem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                ("points", models.PositiveIntegerField(verbose_name="امتیاز")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="shop.coupon",
                        verbose_name="کد تخفیف",
                    ),
                ),
            ],
            options={
                "verbose_name": "تبدیل امتیاز",
                "verbose_name_plural": "تبدیل\u200cهای امتیاز",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seen_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "product")},
            },
        ),
    ]
