# Generated by Django 5.2.17 on 2026-10-09 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_update_default_texts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="smslog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order", "ثبت سفارش"),
                    ("admin", "خبر به مدیر"),
                    ("paid", "پرداخت موفق"),
                    ("status", "تغییر وضعیت"),
                    ("remind", "یادآوری پرداخت"),
                    ("campaign", "کمپین"),
                    ("winback", "بازگشت مشتری"),
                    ("birthday", "تولد"),
                    ("cart", "سبد رهاشده"),
                    ("review", "جایزهٔ نظر"),
                    ("invite", "دعوت به نظر"),
                    ("alert", "خبرم کن"),
                    ("inst", "اقساط"),
                    ("market", "مارکت\u200cپلیس"),
                    ("bulk", "پیامک گروهی"),
                    ("manual", "پیامک دستی"),
                    ("other", "سایر"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="نوع",
            ),
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                ("text", models.TextField(verbose_name="یادداشت")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
