# Generated by Django 5.2.17 on 2026-10-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_smslog_kind_customernote"),
        ("shop", "0011_shopsettings_busy_enabled_shopsettings_busy_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="مناسبت")),
                ("enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "فروردین"),
                            (2, "اردیبهشت"),
                            (3, "خرداد"),
                            (4, "تیر"),
                            (5, "مرداد"),
                            (6, "شهریور"),
                            (7, "مهر"),
                            (8, "آبان"),
                            (9, "آذر"),
                            (10, "دی"),
                            (11, "بهمن"),
                            (12, "اسفند"),
                        ],
                        verbose_name="ماه شمسی",
                    ),
                ),
                ("day", models.PositiveSmallIntegerField(verbose_name="روز")),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="ساعت ارسال"
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            (
                                "all",
                                "همه (خریداران، سفارش ناتمام و ثبت\u200cنامی\u200cها)",
                            ),
                            ("buyers", "همهٔ خریداران"),
                            ("inactive", "خریدارانی که مدتی نخریده\u200cاند"),
                            ("vip", "مشتریان وفادار"),
                            ("active", "فعال (خرید در ۶ ماه اخیر)"),
                            ("new", "خریداران تازه (۶۰ روز اخیر)"),
                            ("at_risk", "در خطر ریزش (۶ تا ۱۲ ماه بی\u200cخرید)"),
                            ("lost", "از دست رفته (بیش از یک سال)"),
                            (
                                "album",
                                "علاقه\u200cمندان یک آلبوم (دیده، در سبد یا سفارش ناتمام)",
                            ),
                            ("unpaid", "سفارش داده ولی هرگز پرداخت نکرده"),
                            ("registered", "ثبت\u200cنام\u200cکرده بدون سفارش"),
                            ("custom", "شماره\u200cهای دلخواه"),
                        ],
                        default="all",
                        max_length=12,
                        verbose_name="گیرنده\u200cها",
                    ),
                ),
                (
                    "inactive_days",
                    models.PositiveIntegerField(
                        default=180, verbose_name="بی\u200cخریدی دست\u200cکم (روز)"
                    ),
                ),
                (
                    "discount",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="۰ یعنی بدون کد تخفیف",
                        verbose_name="مبلغ تخفیف (تومان)",
                    ),
                ),
                (
                    "min_order",
                    models.PositiveBigIntegerField(
                        default=40000000, verbose_name="حداقل خرید (تومان)"
                    ),
                ),
                (
                    "valid_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="مهلت کد (روز)"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="متغیرها: {name} {code} {discount} {min} {until} {site}",
                        verbose_name="متن پیامک",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="یادداشت"
                    ),
                ),
                (
                    "last_run_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="آخرین سال ارسال",
                    ),
                ),
                (
                    "preview_year",
                    models.PositiveSmallIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "مناسبت تقویم پیامکی",
                "verbose_name_plural": "تقویم کمپین\u200cهای خودکار",
                "ordering": ["month", "day"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                help_text="برای متغیرهای {product} {size} {percent} {left} {link}",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="shop.specialoffer",
                verbose_name="فرصت ویژه",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="calendar_preview",
            field=models.BooleanField(
                default=True,
                help_text="یک روز پیش از هر کمپین خودکار، متن و تعداد گیرنده\u200cها برای مدیران پیامک می\u200cشود تا اگر خواستند خاموشش کنند",
                verbose_name="پیش\u200cنمایش کمپین\u200cهای تقویم برای مدیران",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="offer_sms_enabled",
            field=models.BooleanField(
                default=True,
                help_text="هر هفته یکی از فرصت\u200cهای ویژه (بیشترین تخفیف، تکراری نه) برای مشتریان پیامک می\u200cشود",
                verbose_name="پیامک هفتگی فرصت ویژه",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="offer_sms_hour",
            field=models.PositiveSmallIntegerField(
                default=11, verbose_name="ساعت ارسال"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="offer_sms_min_percent",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name="کمترین تخفیف برای ارسال (٪)"
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="offer_sms_segment",
            field=models.CharField(
                choices=[
                    ("all", "همه (خریداران، سفارش ناتمام و ثبت\u200cنامی\u200cها)"),
                    ("buyers", "همهٔ خریداران"),
                    ("active", "خریداران فعال"),
                    ("at_risk", "در خطر ریزش"),
                    ("registered", "ثبت\u200cنام\u200cکرده بدون سفارش"),
                ],
                default="all",
                max_length=12,
                verbose_name="گیرنده\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="offer_sms_text",
            field=models.TextField(
                default="{name} عزیز، فرصت ویژهٔ این هفته در ایران کارپت: {product} ({size}) با {percent}٪ تخفیف و آمادهٔ ارسال فوری. {left}\n{link}",
                verbose_name="متن پیامک فرصت ویژه",
            ),
        ),
        migrations.AddField(
            model_name="crmsettings",
            name="offer_sms_weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (5, "شنبه"),
                    (6, "یکشنبه"),
                    (0, "دوشنبه"),
                    (1, "سه\u200cشنبه"),
                    (2, "چهارشنبه"),
                    (3, "پنجشنبه"),
                    (4, "جمعه"),
                ],
                default=5,
                verbose_name="روز ارسال",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="segment",
            field=models.CharField(
                choices=[
                    ("all", "همه (خریداران، سفارش ناتمام و ثبت\u200cنامی\u200cها)"),
                    ("buyers", "همهٔ خریداران"),
                    ("inactive", "خریدارانی که مدتی نخریده\u200cاند"),
                    ("vip", "مشتریان وفادار"),
                    ("active", "فعال (خرید در ۶ ماه اخیر)"),
                    ("new", "خریداران تازه (۶۰ روز اخیر)"),
                    ("at_risk", "در خطر ریزش (۶ تا ۱۲ ماه بی\u200cخرید)"),
                    ("lost", "از دست رفته (بیش از یک سال)"),
                    (
                        "album",
                        "علاقه\u200cمندان یک آلبوم (دیده، در سبد یا سفارش ناتمام)",
                    ),
                    ("unpaid", "سفارش داده ولی هرگز پرداخت نکرده"),
                    ("registered", "ثبت\u200cنام\u200cکرده بدون سفارش"),
                    ("custom", "شماره\u200cهای دلخواه"),
                ],
                default="buyers",
                max_length=12,
                verbose_name="گیرنده\u200cها",
            ),
        ),
    ]
