# Generated by Django 5.2.17 on 2026-10-09 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_seed_calendar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crmsettings",
            name="contact_admin_sms",
            field=models.BooleanField(
                default=True,
                help_text="به شماره\u200cهای مدیر (زبانهٔ «فروش و ارسال»)؛ فقط نام و پیوند پیام، نه متن آن.",
                verbose_name="پیامک خبر پیام تازهٔ «تماس با ما» به مدیران",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order", "ثبت سفارش"),
                    ("admin", "خبر به مدیر"),
                    ("paid", "پرداخت موفق"),
                    ("status", "تغییر وضعیت"),
                    ("remind", "یادآوری پرداخت"),
                    ("campaign", "کمپین"),
                    ("winback", "بازگشت مشتری"),
                    ("birthday", "تولد"),
                    ("cart", "سبد رهاشده"),
                    ("review", "جایزهٔ نظر"),
                    ("invite", "دعوت به نظر"),
                    ("alert", "خبرم کن"),
                    ("inst", "اقساط"),
                    ("market", "مارکت\u200cپلیس"),
                    ("bulk", "پیامک گروهی"),
                    ("manual", "پیامک دستی"),
                    ("contact", "پاسخ تماس با ما"),
                    ("other", "سایر"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="نوع",
            ),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="نام")),
                (
                    "mobile",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("buy", "مشاوره و خرید"),
                            ("order", "پیگیری سفارش"),
                            ("inst", "خرید اقساطی"),
                            ("coop", "همکاری"),
                            ("complaint", "انتقاد و شکایت"),
                            ("other", "سایر"),
                        ],
                        default="buy",
                        max_length=10,
                        verbose_name="موضوع",
                    ),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "تازه"),
                            ("answered", "پاسخ داده شد"),
                            ("archived", "بایگانی"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reply",
                    models.TextField(
                        blank=True,
                        help_text="بعد از «ذخیره» به موبایل فرستنده پیامک می\u200cشود. اگر بعداً متن را عوض کنید، متن تازه دوباره فرستاده می\u200cشود.",
                        verbose_name="پاسخ (با پیامک فرستاده می\u200cشود)",
                    ),
                ),
                ("reply_sent", models.TextField(blank=True, editable=False)),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="زمان پاسخ"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="یادداشت داخلی"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(blank=True, editable=False, null=True),
                ),
                ("page", models.CharField(blank=True, editable=False, max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان"
                    ),
                ),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام تماس با ما",
                "verbose_name_plural": "پیام\u200cهای تماس با ما",
                "ordering": ["-created_at"],
            },
        ),
    ]
