# Generated by Django 5.2.17 on 2026-10-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="link_path",
            field=models.CharField(
                blank=True,
                help_text="مسیر صفحه\u200cای در سایت، مثل /فرش-جشنواره-ای/ ؛ خالی = صفحهٔ فرش فرصت ویژه (اگر انتخاب شده) یا صفحهٔ اول",
                max_length=300,
                verbose_name="مقصد {link}",
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="crm.campaign",
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="first_click_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="mobile",
            field=models.CharField(blank=True, db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="text",
            field=models.TextField(
                default="{name} عزیز، به پاس خرید قبلی\u200cتان از ایران کارپت، کد تخفیف {discount} تومانی برای شما:\n{code}\nبرای خرید بالای {min} تومان، تا {until}. {site}",
                help_text="{name} نام، {code} کد تخفیف شخصی، {discount} مبلغ تخفیف، {min} حداقل خرید، {until} تاریخ پایان، {link} پیوند کوتاه شخصی (کلیک هر نفر و خریدش در گزارش کمپین دیده می\u200cشود)، {site} نشانی سایت (بدون آمار)",
                verbose_name="متن پیامک",
            ),
        ),
    ]
