# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="مثلاً reeds-per-meter",
                        max_length=100,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="آدرس آرشیو: /<نامک ویژگی>/<نامک مقدار>/",
                        verbose_name="صفحهٔ آرشیو دارد",
                    ),
                ),
                (
                    "show_in_filters",
                    models.BooleanField(default=True, verbose_name="در فیلترها"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی\u200cها",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="نام انگلیسی"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="توضیحات کامل (HTML)"),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="توضیح کوتاه"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("publish", "منتشرشده"),
                            ("draft", "پیش\u200cنویس"),
                            ("private", "خصوصی"),
                        ],
                        db_index=True,
                        default="publish",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("simple", "ساده"), ("variable", "متغیر (چند سایز)")],
                        default="variable",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد کالا"
                    ),
                ),
                (
                    "custom_base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اگر پر شود به\u200cجای قیمت پایهٔ آلبوم استفاده می\u200cشود",
                        max_digits=20,
                        null=True,
                        verbose_name="قیمت پایهٔ اختصاصی",
                    ),
                ),
                (
                    "sale_status",
                    models.CharField(
                        choices=[
                            ("available", "موجود"),
                            ("unavailable", "ناموجود"),
                            ("showroom", "نمایشگاهی"),
                            ("coming_soon", "به\u200cزودی"),
                            ("inquiry_only", "استعلام قیمت"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="وضعیت فروش",
                    ),
                ),
                (
                    "min_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="کمترین قیمت",
                    ),
                ),
                (
                    "max_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="بیشترین قیمت",
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("instock", "موجود"),
                            ("outofstock", "ناموجود"),
                            ("onbackorder", "پیش\u200cسفارش"),
                        ],
                        db_index=True,
                        default="instock",
                        max_length=20,
                        verbose_name="موجودی",
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="میانگین امتیاز",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد امتیاز"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="بازدید"),
                ),
                ("menu_order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ انتشار",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="آخرین ویرایش"
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "تصویر گالری",
                "verbose_name_plural": "گالری تصاویر",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "برچسب محصول",
                "verbose_name_plural": "برچسب\u200cهای محصول",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("author_name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "author_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="امتیاز"
                    ),
                ),
                ("content", models.TextField(verbose_name="متن")),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="تأییدشده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ"
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر محصول",
                "verbose_name_plural": "نظرات محصول",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=100, verbose_name="کد"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                ("menu_order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "override_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="اگر پر شود، به\u200cجای فرمول آلبوم استفاده می\u200cشود (markup و حمل همچنان اعمال می\u200cشود)",
                        max_digits=20,
                        null=True,
                        verbose_name="قیمت خرید اختصاصی",
                    ),
                ),
                (
                    "manual_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="برای محصولی که آلبوم ندارد",
                        null=True,
                        verbose_name="قیمت نهایی دستی",
                    ),
                ),
                (
                    "sale_price",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="قیمت حراج (نهایی)"
                    ),
                ),
                (
                    "pair_only",
                    models.BooleanField(
                        blank=True,
                        help_text="خالی = پیش\u200cفرض سایز",
                        null=True,
                        verbose_name="فقط زوج",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="موجود"),
                ),
                (
                    "final_price",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        null=True,
                        verbose_name="قیمت نهایی",
                    ),
                ),
                (
                    "purchase_price",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, verbose_name="قیمت خرید"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنوع (سایز)",
                "verbose_name_plural": "تنوع\u200cها (سایزها)",
                "ordering": ["menu_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="AttributeTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="مقدار")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=255, verbose_name="نامک"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="catalog.attribute",
                        verbose_name="ویژگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ویژگی",
                "verbose_name_plural": "مقادیر ویژگی",
                "ordering": ["attribute", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=255,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.media",
                    ),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="توضیحات متا"),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="کلمهٔ کلیدی"
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً noindex,nofollow — خالی یعنی index,follow",
                        max_length=100,
                        verbose_name="robots",
                    ),
                ),
                (
                    "canonical_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="canonical"
                    ),
                ),
                (
                    "wp_id",
                    models.PositiveBigIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=255, verbose_name="نامک"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات (HTML)"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.media",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دستهٔ محصول",
                "verbose_name_plural": "دسته\u200cهای محصول",
                "ordering": ["order", "name"],
            },
        ),
    ]
