# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="pricing.album",
                verbose_name="آلبوم قیمت",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.brand",
                verbose_name="برند",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.category",
                verbose_name="دسته\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.media",
                verbose_name="تصویر اصلی",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_products",
                to="catalog.category",
                verbose_name="دستهٔ اصلی",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="specs",
            field=models.ManyToManyField(
                blank=True,
                help_text="ویژگی\u200cهای ثابت محصول (شانه، تراکم، جنس نخ و...)",
                related_name="products",
                to="catalog.attributeterm",
                verbose_name="مشخصات",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.media",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery",
            field=models.ManyToManyField(
                blank=True,
                related_name="gallery_products",
                through="catalog.ProductImage",
                to="core.media",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.producttag",
                verbose_name="برچسب\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="catalog.review",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="variations",
                to="catalog.attributeterm",
                verbose_name="سایر ویژگی\u200cها (رنگ و...)",
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.media",
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variations",
                to="pricing.size",
                verbose_name="سایز",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attributeterm",
            unique_together={("attribute", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("parent", "slug")},
        ),
    ]
