# Generated by Django 5.2.17 on 2026-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="خالی بگذارید تا خودکار ساخته شود",
                max_length=100,
                verbose_name="کد کالا",
            ),
        ),
    ]
