# Generated by Django 5.2.17 on 2026-10-05 12:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_filter_attrs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="پیوند ویدیو در آپارات (aparat.com/v/...) یا فایل mp4. در صفحهٔ فرش و نتایج گوگل نمایش داده می\u200cشود.",
                max_length=400,
                verbose_name="ویدیوی فرش",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="mobile",
            field=models.CharField(blank=True, max_length=11, verbose_name="موبایل"),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="نظر از طرف کسی که همین فرش را خریده",
                verbose_name="خریدار این فرش",
            ),
        ),
        migrations.CreateModel(
            name="ReviewPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="reviews/%Y/%m/", verbose_name="عکس"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "عکس نظر",
                "verbose_name_plural": "عکس\u200cهای نظر",
            },
        ),
    ]
