# Generated by Django 5.2.17 on 2026-10-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_reviews_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="تعداد رنگ"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="custom_note",
            field=models.TextField(
                blank=True,
                help_text="یک یا دو جملهٔ مخصوص همین فرش (مثلاً حس طرح یا پیشنهاد اتاق)؛ جای {یادداشت} در قالب می\u200cنشیند.",
                verbose_name="یادداشت اختصاصی",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="design_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="مثل «آرشان». فرش\u200cهای هم\u200cآلبوم با نقشهٔ یکسان، «رنگ\u200cهای دیگر» همدیگر نشان داده می\u200cشوند.",
                max_length=120,
                verbose_name="نام نقشه",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="use_template",
            field=models.BooleanField(
                default=False,
                help_text="روشن: توضیحات و خلاصه از «قالب متن محصول» ساخته می\u200cشود و با قیمت و تنظیمات به\u200cروز می\u200cماند؛ متن دستی بالا نگه داشته می\u200cشود ولی نمایش داده نمی\u200cشود.",
                verbose_name="متن از قالب",
            ),
        ),
    ]
