# Generated by Django 5.2.17 on 2026-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_fill_design"),
        ("pricing", "0004_price_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="only_sizes",
            field=models.ManyToManyField(
                blank=True,
                help_text="خالی = همهٔ سایزهای آلبوم. مثلاً برای محصول جدای «فرش گرد قطر ۱٫۵» فقط همان سایز را انتخاب کنید؛ قیمتش از همان آلبوم می\u200cآید و فرش اصلی هم همهٔ سایزهایش را نگه می\u200cدارد.",
                related_name="+",
                to="pricing.size",
                verbose_name="فقط این سایزهای آلبوم",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="single_sizes",
            field=models.ManyToManyField(
                blank=True,
                help_text="سایزهایی که در آلبوم «فقط جفت» هستند ولی در این محصول یک\u200cتخته هم سفارش گرفته می\u200cشوند.",
                related_name="+",
                to="pricing.size",
                verbose_name="این سایزها تکی هم فروخته شوند",
            ),
        ),
    ]
