# Generated by Django 5.2.17 on 2026-10-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_size_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="search_text",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="product",
            name="search_title",
            field=models.CharField(blank=True, editable=False, max_length=600),
        ),
    ]
