# Generated by Django 5.2.17 on 2026-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_fill_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="review_note",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="پیام بررسی به فروشنده"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "در انتظار بررسی"),
                    ("approved", "تأیید شد"),
                    ("rejected", "رد شد"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="بررسی",
            ),
        ),
    ]
