# Generated by Django 5.2.17 on 2026-10-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_review_note_product_review_status"),
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی کالای خود ایران کارپت",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="market.seller",
                verbose_name="فروشنده",
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="stock_qty",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="خالی = بی\u200cشمار. با هر سفارش پرداخت\u200cشده کم می\u200cشود و در صفر ناموجود می\u200cشود.",
                null=True,
                verbose_name="تعداد موجودی",
            ),
        ),
    ]
