# Generated by Django 5.2.17 on 2026-10-05 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0006_product_content"),
        ("pricing", "0004_price_list"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prep_time",
                    models.CharField(
                        default="۱۰ تا ۱۴ روز کاری",
                        help_text="متغیر {زمان_آماده_سازی}",
                        max_length=80,
                        verbose_name="زمان آماده\u200cسازی",
                    ),
                ),
                (
                    "shipping_cost",
                    models.CharField(
                        default="حدود ۲۰۰ تا ۵۰۰ هزار تومان",
                        help_text="متغیر {هزینه_ارسال}؛ کلی، نه برای هر سایز",
                        max_length=120,
                        verbose_name="هزینهٔ ارسال (پس\u200cکرایه)",
                    ),
                ),
                (
                    "cancel_penalty",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="متغیر {جریمه_لغو}",
                        verbose_name="درصد جریمهٔ لغو",
                    ),
                ),
                (
                    "pair_colors",
                    models.CharField(
                        default="آبی، زرد، لاکی، کرم",
                        help_text="با ویرگول جدا کنید. برای فرش\u200cهای این رنگ\u200cها متغیر {جفتی} جملهٔ زیر را می\u200cگذارد.",
                        max_length=255,
                        verbose_name="رنگ\u200cهایی که معمولاً جفتی بافته می\u200cشوند",
                    ),
                ),
                (
                    "pair_note",
                    models.CharField(
                        default="فرش\u200cهای زمینهٔ {رنگ} معمولاً جفتی بافته می\u200cشوند؛ اگر فقط یک تخته می\u200cخواهید، پیش از سفارش با کارشناس هماهنگ کنید.",
                        max_length=300,
                        verbose_name="جملهٔ جفتی",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        default="۵ سال ضمانت",
                        help_text="متغیر {ضمانت}",
                        max_length=200,
                        verbose_name="ضمانت (یک خط)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات متن محصولات",
                "verbose_name_plural": "تنظیمات متن محصولات",
            },
        ),
        migrations.CreateModel(
            name="ContentEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("summary", models.CharField(max_length=300)),
                ("backup", models.JSONField(default=list)),
                ("undone", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام قالب")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="برای فرش\u200cهایی که آلبوم و دسته\u200cشان قالب جدا ندارد.",
                        verbose_name="قالب پیش\u200cفرض",
                    ),
                ),
                (
                    "title_pattern",
                    models.CharField(
                        default="فرش {شانه} شانه[[ {برجسته}]] نقشه {نقشه} زمینه {رنگ}",
                        help_text="فقط برای ساخت گروهی فرش\u200cها. بخش داخل [[ ]] فقط وقتی می\u200cآید که متغیرهایش مقدار داشته باشند.",
                        max_length=255,
                        verbose_name="الگوی عنوان (ساخت گروهی)",
                    ),
                ),
                (
                    "bullets",
                    models.TextField(
                        blank=True,
                        help_text="هر خط یک مورد. متغیرها را در آکولاد بنویسید، مثل {نقشه}. راهنمای کامل متغیرها پایین همین صفحه است.",
                        verbose_name="خلاصهٔ کنار قیمت",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="خطی که با ## شروع شود تیتر است و خطی که با - شروع شود فهرست. متغیرها را در آکولاد بنویسید، مثل {نقشه}. راهنمای کامل متغیرها پایین همین صفحه است.",
                        verbose_name="متن توضیحات",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین تغییر"),
                ),
                (
                    "albums",
                    models.ManyToManyField(
                        blank=True,
                        help_text="فرش\u200cهای این آلبوم\u200cها از این قالب استفاده می\u200cکنند.",
                        related_name="content_templates",
                        to="pricing.album",
                        verbose_name="برای آلبوم\u200cهای",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اگر آلبوم فرش قالب جدا نداشت، قالب دستهٔ آن به\u200cکار می\u200cرود.",
                        related_name="content_templates",
                        to="catalog.category",
                        verbose_name="یا برای دسته\u200cهای",
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب متن محصول",
                "verbose_name_plural": "قالب\u200cهای متن محصول",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="InfoBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "body",
                    models.TextField(
                        help_text="خطی که با - شروع شود فهرست است. متغیرها را در آکولاد بنویسید، مثل {نقشه}. راهنمای کامل متغیرها پایین همین صفحه است.",
                        verbose_name="متن",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "is_open",
                    models.BooleanField(
                        default=False, verbose_name="باز نمایش داده شود"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "albums",
                    models.ManyToManyField(
                        blank=True,
                        help_text="خالی = همهٔ فرش\u200cها",
                        related_name="+",
                        to="pricing.album",
                        verbose_name="فقط برای آلبوم\u200cهای",
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش مشترک صفحهٔ فرش",
                "verbose_name_plural": "بخش\u200cهای مشترک صفحهٔ فرش",
                "ordering": ["order", "pk"],
            },
        ),
    ]
