# Generated by Django 5.2.17 on 2026-10-03 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotFoundLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("hits", models.PositiveIntegerField(default=1)),
                ("referrer", models.CharField(blank=True, max_length=1000)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "خطای ۴۰۴",
                "verbose_name_plural": "گزارش خطاهای ۴۰۴",
                "ordering": ["-hits"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        db_index=True,
                        help_text="بدون دامنه و بدون / ابتدا و انتها؛ فارسی (decode\u200cشده). مثلاً product/نام-قدیمی",
                        max_length=500,
                        verbose_name="آدرس مبدأ",
                    ),
                ),
                (
                    "match",
                    models.CharField(
                        choices=[
                            ("exact", "دقیق"),
                            ("start", "شروع با"),
                            ("regex", "عبارت باقاعده"),
                        ],
                        default="exact",
                        max_length=10,
                        verbose_name="نوع تطبیق",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="برای 410 خالی بماند",
                        max_length=1000,
                        verbose_name="آدرس مقصد",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (301, "301 دائمی"),
                            (302, "302 موقت"),
                            (410, "410 حذف\u200cشده"),
                        ],
                        default=301,
                        verbose_name="کد",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="فعال"
                    ),
                ),
                (
                    "hits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده"
                    ),
                ),
                ("last_hit", models.DateTimeField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        help_text="rankmath / old_slug / brand_merge / manual",
                        max_length=50,
                        verbose_name="منشأ",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "ریدایرکت",
                "verbose_name_plural": "ریدایرکت\u200cها",
                "ordering": ["-hits"],
            },
        ),
    ]
