# Generated by Django 5.2.17 on 2026-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indexnow_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="هر بار محصول، قیمت، مقاله یا برگه تغییر کند، نشانی\u200cاش فوراً به Bing و Yandex خبر داده می\u200cشود.",
                        verbose_name="ارسال خودکار به IndexNow",
                    ),
                ),
                (
                    "indexnow_key",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="کلید IndexNow",
                    ),
                ),
                (
                    "indexnow_last_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="آخرین ارسال",
                    ),
                ),
                (
                    "indexnow_last_status",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=300,
                        verbose_name="نتیجهٔ آخرین ارسال",
                    ),
                ),
                (
                    "indexnow_total",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="تعداد نشانی\u200cهای ارسال\u200cشده",
                    ),
                ),
                (
                    "bing_verification",
                    models.CharField(
                        blank=True,
                        help_text="فقط مقدار content از تگ msvalidate.01 که Bing Webmaster Tools می\u200cدهد؛ مثل 1A2B3C4D5E...",
                        max_length=100,
                        verbose_name="کد تأیید Bing",
                    ),
                ),
                (
                    "llms_about",
                    models.TextField(
                        blank=True,
                        help_text="چند جملهٔ روشن و دقیق دربارهٔ ایران کارپت (از کی فعالید، کجا هستید، از کدام کارخانه\u200cها می\u200cفروشید، ارسال، ضمانت و...). بالای فایل /llms.txt می\u200cآید.",
                        verbose_name="معرفی فروشگاه برای هوش مصنوعی",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سئو و هوش مصنوعی",
                "verbose_name_plural": "تنظیمات سئو و هوش مصنوعی",
            },
        ),
    ]
