# Generated by Django 5.2.17 on 2026-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0002_seo_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_branch",
            field=models.CharField(
                blank=True, default="main", max_length=50, verbose_name="شاخه"
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_enabled",
            field=models.BooleanField(
                default=True,
                help_text="روزی یک مقالهٔ بازنویسی\u200cشده (به ترتیب اولویت) روی همان نشانی قبلی منتشر می\u200cشود؛ نسخهٔ قبلی نگه داشته می\u200cشود.",
                verbose_name="انتشار خودکار مقاله\u200cهای بازنویسی\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_hour",
            field=models.PositiveSmallIntegerField(
                default=9,
                help_text="به وقت تهران، ۰ تا ۲۳",
                verbose_name="ساعت انتشار روزانه",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_last_status",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=300,
                verbose_name="نتیجهٔ آخرین دریافت",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_last_sync",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="آخرین دریافت از گیت\u200cهاب",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_per_day",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="تعداد انتشار در روز"
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_repo",
            field=models.CharField(
                blank=True,
                default="itwman/irancarpet",
                help_text="متن\u200cهای تازه از پوشهٔ content/rewrites/posts این مخزن خوانده می\u200cشود",
                max_length=100,
                verbose_name="مخزن گیت\u200cهاب متن\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="rewrite_review_days",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="متن تازه این مدت در پنل می\u200cماند تا اگر خواستید ویرایش یا رد کنید؛ بعد خودکار منتشر می\u200cشود.",
                verbose_name="مهلت بررسی (روز)",
            ),
        ),
    ]
