# Generated by Django 5.2.17 on 2026-10-09 10:38

from django.db import migrations, models


def two_per_day(apps, schema_editor):
    apps.get_model("seo", "SeoSettings").objects.filter(rewrite_per_day=1).update(rewrite_per_day=2)


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0003_seosettings_rewrite_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seosettings",
            name="rewrite_per_day",
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name="تعداد انتشار در روز"
            ),
        ),
        migrations.RunPython(two_per_day, migrations.RunPython.noop),
    ]
