# Generated by Django 5.2.17 on 2026-10-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0004_alter_seosettings_rewrite_per_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seosettings",
            name="rewrite_enabled",
            field=models.BooleanField(
                default=True,
                help_text="هر روز به «تعداد انتشار در روز» مقالهٔ بازنویسی\u200cشده (به ترتیب اولویت) روی همان نشانی قبلی منتشر می\u200cشود؛ نسخهٔ قبلی نگه داشته می\u200cشود.",
                verbose_name="انتشار خودکار مقاله\u200cهای بازنویسی\u200cشده",
            ),
        ),
    ]
